### ISSUE TITLE
Privacy issue adding employes to an organization

### ISSUE THREAD

**Issue by mbo-s** [cross-solution/YAWIK#101]
You can add employees to an organization e.g. http://yawik.org/demo/de/organizations/edit/545cfe12ae02594227615841
and the search returns the email from every matched user.

Better would be add employees by email, if the email exists the user X get a notification that user Y wants to add him as an employee to organization Z, otherwise send an invitation to the email from user X with the same information.

**Comment by cbleek** [comment]
Inviting employees by mail is planned. The upcoming feature to create a own company with employees will simply search over all registered users. The pricavy issue is known. An inviting workflow will be added in a later version.

Regards,

Carsten

**Comment by TiSiE** [comment]
Invitations of employees is addressed in #115 .
