### ISSUE TITLE
Exception in last step of job creation

### ISSUE THREAD

**Issue by mbo-s** [cross-solution/YAWIK#102]
Error message is:

An error occurred
An error occurred during execution; please try again later.
Additional information:
Zend\Mail\Exception\InvalidArgumentException
File:
/var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/Mail/Message.php:512
Message:
Zend\Mail\Message::addTo expects a string, AddressInterface, array, AddressList, or Traversable as its first argument; received "NULL"
Stack trace:
#0 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/Mail/Message.php(169): Zend\Mail\Message->updateAddressList(Object(Zend\Mail\AddressList), NULL, NULL, 'Zend\Mail\Messa...')
#1 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/Mail/Message.php(154): Zend\Mail\Message->addTo(NULL, NULL)
#2 /var/www/clients/client1/web26/cross-applicant-management/module/Jobs/src/Jobs/Listener/StatusChanged.php(84): Zend\Mail\Message->setTo(NULL)
#3 [internal function]: Jobs\Listener\StatusChanged->__invoke(Object(Jobs\Listener\Events\JobEvent))
#4 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Object(Jobs\Listener\StatusChanged), Object(Jobs\Listener\Events\JobEvent))
#5 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('job.created', Object(Jobs\Listener\Events\JobEvent), Array)
#6 /var/www/clients/client1/web26/cross-applicant-management/module/Jobs/src/Jobs/Controller/ManageController.php(322): Zend\EventManager\EventManager->trigger('job.created', Object(Jobs\Listener\Events\JobEvent))
#7 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractActionController.php(83): Jobs\Controller\ManageController->completionAction()
#8 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#9 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#10 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractController.php(117): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/Mvc/DispatchListener.php(114): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#13 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#14 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#15 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#16 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(309): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#17 /var/www/clients/client1/web26/cross-applicant-management/public/index.php(32): Zend\Mvc\Application->run()
#18 {main}

**Comment by cbleek** [comment]
The mechanism to set the approval Mail was changed.

  cp module/Jobs/config/module.jobs.options.local.php.dist config/autoload/module.jobs.options.local.php

Then adjust the "multipostingApprovalMail" Parameter in config/autoload/module.jobs.options.local.php

Thank's for reporting. We'll modify the docs on http://yawik.rtfd.org/

Regards,

Carsten
