### ISSUE TITLE
Delete Account is not implemented

### ISSUE THREAD

**Issue by mbo-s** [cross-solution/YAWIK#103]
There is no possibility to delete the account.

**Comment by TiSiE** [comment]
There are several complications deleting an user account

* What is happening to the jobs created by the user?
* What is happening to the applications the user has committed?
* What is happening with the users' organization and the assigned employees?

**Comment by mbo-s** [comment]
If a user wants to delete his account, you can send him to a confirmation page, where everything is listed, what will be deleted:
* Jobs he created
* Applications he submitted
* Organizations and Employees
* Other things he uploaded

As an enhancement the user could for his organizations/jobs choose another person/account who will manage them

**Comment by TiSiE** [comment]
That's a nice idea...

**Comment by cbleek** [comment]
We can inactivate accounts now. 

Deleting Users well be don in 0.26

**Comment by TiSiE** [comment]
@fedys If you don't mind, please implement this feature. In the first step, just the listing of related objects that will be removed should be shown and a confirm and cancel button.

**Comment by fedys** [comment]
@TiSiE No problem, I will implemented. I am busy this week. I will start on it next week.

**Comment by TiSiE** [comment]
@fedys: Nevermind, @cbleek is always keen to have new features available :smirk:
Just do the tests and reopen the pr or create a new one (I don't know what's easier with github...)
