### ISSUE TITLE
every recruiter can edit all joboffers

### ISSUE THREAD

**Issue by mbo-s** [cross-solution/YAWIK#104]
Create a new account on and change role to recruiter, if not set.

Create a new job, it has now the status draft.
Copy the JobID

Log out and log in with another recruiter account e.g. demo/demo

manually call with the copied JobID
http://yawik.org/demo/en/jobs/edit?id=JOBID

Alternative:
go to the jobboard: http://yawik.org/demo/en/jobboard
Take the JobID from an job offer e.g.
http://yawik.org/demo/en/jobs/view?id=5475ca7bae0259171e67376a

Log in with an new recruiter Account an open
http://yawik.org/demo/en/jobs/edit?id=5475ca7bae0259171e67376a

You have now full access to the job and can edit everything.

**Comment by cbleek** [comment]
Yes, the ACL Check is currently commentet.

https://github.com/cross-solution/YAWIK/blob/develop/module/Jobs/src/Jobs/Controller/ManageController.php#L107

If the check is enabled via

        $this->acl($jobEntity, 'edit');

and if you take some foreign ID, you'll get a fatal error. 

    Fatal error: Call to a member function getId() on a non-object in /home/cbleek/Projects/YAWIK/module/Jobs/src/Jobs/Acl/WriteAssertion.php on line 47

**Comment by TiSiE** [comment]
WriteAssertion was changed with e602a16 

The error will be fixed when #87 is finished
