### ISSUE TITLE
unable to allow upload docx-files as attchment in application

### ISSUE THREAD

**Issue by mbo-s** [cross-solution/YAWIK#107]
If I add application/vnd.openxmlformats-officedocument.wordprocessingml.document as an allowed 
MimeTpye in config/autoload/applications.forms.global.php

'attachmentsMimeType' => array('image','application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document'),

and then select an docx-file as an attachment in an application the file is rejected with the message "The file type is not supported".

The input field has the correct mimetypes:
&lt;input name="attachments" class="hide" multiple="multiple" data-maxsize="500000" data-allowedtypes="image,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" data-maxfilecount="5" id="attachments-attachments" type="file"&gt;

Adding doc-files works with application/msword.

For the Mimetype see https://technet.microsoft.com/en-us/library/ee309278%28office.12%29.aspx

**Comment by TiSiE** [comment]
I tried to reproduce this error and cannot confirm the behaviour.

Uploading a docx document with Firefox 38 worked for me.

Please provide the document you used so I can further examine this issue.

**Comment by TiSiE** [comment]
I will close this issue. 
But still feel free to provide the file, I will reopen the issue then.

**Comment by mbo-s** [comment]
e.g. http://www.yawik.org/demo/en/apply/55f01d25c5105c8448eb1495

github does not support the *.doc file type, so i can't upload it here. It is simple an empty *.doc Document that you can create either with MS Word or Openoffice save as Word-97-file



[empty-docx.docx](https://github.com/cross-solution/YAWIK/files/3728/empty-docx.docx)
![yawik-error-docx](https://cloud.githubusercontent.com/assets/9078194/10140599/acd296da-6608-11e5-9d50-f8d8f937db2a.jpg)

**Comment by TiSiE** [comment]
Still, I downloaded your file from the link, set the MIME type in the attachmentsMimeType key of the configuration file and it worked! 

So this error is still not reproducable.
![docx-upload](https://cloud.githubusercontent.com/assets/2029304/16085922/09c875ac-331e-11e6-9d49-f6aa0ab7c8b0.png)
