### ISSUE TITLE
in some cases the entered jobtext is not saved

### ISSUE THREAD

**Issue by mbo-s** [cross-solution/YAWIK#109]
If you create a new job and then enter text in one of the fields and then click the button "next to preview the job" or change the template, the current text is lost.
If you enter some text and then click somewhere else, so the editor loses the focus the text is saved

**Comment by mathias-weitz-cross-solutions** [comment]
for the chance, that a user misses to submit the entered data,
a confirmation-box pops up.
For some more rare cases (like tinyMC) an autosave is implemented, that delays the execution of jumping to a new page until all content is saved.
