### ISSUE TITLE
Navbar on small screen size broken

### ISSUE THREAD

**Issue by mbo-s** [cross-solution/YAWIK#111]
The upper right button on small screens has no function.
A user can't login or use other naviagtion links e.g. go to jobboard.

Steps to reproduce:
open http://www.yawik.org/demo/en with a phone or resize your browser to width < 768px

![yawik-navbar-bug](https://cloud.githubusercontent.com/assets/9078194/6637349/a6f181e4-c979-11e4-86f1-76c705ae7603.jpg)

**Comment by cbleek** [comment]
This was a bug in the YawikDemoSkin.

The data-target in

     <button class="navbar-toggle collapsed" data-target=".yk-navbar-collapse" data-toggle="collapse"
                    type="button">

must match the class of the div container which holds the navigation

  <nav id="main-navigation" class="navbar-collapse collapse yk-navbar-collapse" role="navigation">
