### ISSUE TITLE
Saving Company Name fails when creating new job

### ISSUE THREAD

**Issue by utrenkner** [cross-solution/YAWIK#113]
Pressing the "save" button gives the following error message "Value is required and can't be empty".

It does however work, when I press enter instead of the "save" button

**Comment by mathias-weitz-cross-solutions** [comment]
Problem confirmed,
in the field "company" you can just enter companies that already exists, 
these have to be created in another formular (very inconvenient, we know).
We are still figuring out how to improve the usability, but we have to ensure that a job has a company that is purposely created and maintained.

**Comment by utrenkner** [comment]
The problem seems different to me: I can change the company name to anything I like as long as I press the enter key. Likewise I can enter anything - including an existing company -, press the save button and get that error message "Value is required and can't be empty".

If only existing companies can be entered, I would suggest to (at least) auto-complete from the list of existing companies. Ideally there should also be a mechanism which proposes to create a company, should it not already exist in the database.

**Comment by cbleek** [comment]
We've changed the input field type from typeahead to select2. The modification is visible in the demo.

This makes the selection of the hireing company fail safe.

The feature will be released in 0.19
