### ISSUE TITLE
Attachment of social profiles is broken

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#120]
The fix in #109 seens to have broken the ability to attache Social Profiles to an application.

When trying to add an social profile, nothings happens.

Error in Firebug:
Error: Permission denied to access property "tinyMCE"

**Comment by mathias-weitz-cross-solutions** [comment]
the problem is caused by the cross-domain-restriction, when we use an iFrame.
This problem linked to the Facebook button. The solution is in the JavaScript that checks not saved content in iFrames, this script must handle an access-denied exception. 
This problem is rare and very easy to solve.

**Comment by cbleek** [comment]
We've removed the fb Like Button from the demo. Adding social profiles works as expected again
