### ISSUE TITLE
Change of user photos format with XING-Login

### ISSUE THREAD

**Issue by blu-IT** [cross-solution/YAWIK#134]
In June 2014 in the XING API forum was announced the following fact:

"Dear developer,
User photos will change from rectangular to square formats. New square formats will be available within the next weeks. The current rectangular images will be available for 6 more months (until January 2015). They will show a square image plus a white bar to stick to the original format (see image). Changes will not go live before Mid July 2014.
If you have any questions at all, please send an e-mail to api-support@xing.com.
Happy developing!
The XING API team"

With the recent dev-version, the photo ha still a white bar.

Regards

**Comment by cbleek** [comment]
thx for the info. by registering via social networks, profile images are imported 1:1. Resizing in view is done via CSS. There ist currently not image manipulation implementet.

Reason: we have not decided which lib to use.

Regards,

Carsten
