### ISSUE TITLE
Possible license issue with mPDF

### ISSUE THREAD

**Issue by utrenkner** [cross-solution/YAWIK#137]
I was looking through the dependencies and found that  YAWIK uses mPDF for PDF generation.
This  may pose a problem as mPDF is licensed under GPL 2.0 but YAWIK is MIT licensed.

The FSF explains their view on the compatibility here (https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.en.html#MereAggregation) [excerpt]:
Combining two modules means connecting them together so that they form a single larger program. If either part is covered by the GPL, the whole combination must also be released under the GPL—if you can't, or won't, do that, you may not combine them.

Especially as the SF-package now even includes mPDF, this may get tricky. Is there any option to swap in another PDF library?

**Comment by cbleek** [comment]
The PDF Download can be disabled by commenting the line

https://github.com/cross-solution/YAWIK/blob/develop/config/config.php#L28

This will remove the Download Link from the detail page of an application. I can confirm the licence problem. 

I would like to see the PDF downloads generated by jspdf. This js  library creates the PDF on the client side. We need the PDF on the server side when forwarding applications. But it should be possible with NodesJS. Other Ideas are welcome.

We're currently not working on this issue.

Thanks for your feedback and regards,

Carsten
