### ISSUE TITLE
Registering with Linkedin

### ISSUE THREAD

**Issue by manager24** [cross-solution/YAWIK#139]
Registering with LinkedIn states an error message. could be the test profile did not have an address or telefonnumber.
Certainly the profil did have an email address but this email address did not transfer to yawik

**Comment by manager24** [comment]
Ein unerwarteter Fehler ist aufgetreten. Bitte kontaktieren Sie den System Administrator
This is the error message... however an account is created

**Comment by cbleek** [comment]
LinkedIn requires the permission "r_emailaddress" to access an email address. 

If only the permission "r_fullprofile" is set (like we've described in the docs), this error occurse.

Thanks for reporting
