### ISSUE TITLE
New registrant can see all jobads plus number of applicants per ad

### ISSUE THREAD

**Issue by manager24** [cross-solution/YAWIK#142]
I created a new recruiter account and this person could instantly without any activities see all jobads plus the name of the relevant recruiter publishing this ad as well as the number of applicants

**Comment by cbleek** [comment]
duplicates #141 , this was fixed in https://github.com/cross-solution/YAWIK/commit/921ebd8d692366b278b1fa5eea0a06d0abc87ae0
