### ISSUE TITLE
Registration email subject is always in english

### ISSUE THREAD

**Issue by mbo-s** [cross-solution/YAWIK#145]
The subject of the registration email is always in english, the email body uses the right language

https://github.com/cross-solution/YAWIK/blob/develop/module/Auth/src/Auth/Service/Register.php#L329

**Comment by mbo-s** [comment]
There are more emails with a fixed english subject,
e.g. password reset
https://github.com/cross-solution/YAWIK/blob/develop/module/Auth/src/Auth/Listener/MailForgotPassword.php#L86

**Comment by cbleek** [comment]
This was fixed in https://github.com/cross-solution/YAWIK/commit/535cf4910913838d22dc1f78908b47d7776c8e37
