### ISSUE TITLE
Input fields on search site using wrong bootstrap-css

### ISSUE THREAD

**Issue by mbo-s** [cross-solution/YAWIK#146]
The search form should use
http://getbootstrap.com/css/#forms-inline
otherwise the input-fields are not on one line
e.g. see https://yawik.org/demo/de/jobboard and zoom in
![yawik-error-form-align](https://cloud.githubusercontent.com/assets/9078194/9738251/f1612550-564a-11e5-8183-abf25a7d1b27.jpg)

**Comment by cbleek** [comment]
This was fixed.
