### ISSUE TITLE
"Javascript disabled" is not translated

### ISSUE THREAD

**Issue by mbo-s** [cross-solution/YAWIK#148]
Javascript is disabled.

JavaScript is required to use this site. Please enable JavaScript and reload.

https://github.com/cross-solution/YAWIK/blob/develop/module/Core/view/layout/_noscript-notice.phtml#L21-L22

**Comment by cbleek** [comment]
the string will be translated, if the view contains

<code>
<?php echo $this->translate('JavaScript is required to use this site. Please enable JavaScript and reload.')?>
</code>

The translate() pattern will ensure, that the string will go to the transifex platform next time, we'll run bin/translate module/Core
