### ISSUE TITLE
German Translation not consistent for password reset

### ISSUE THREAD

**Issue by mbo-s** [cross-solution/YAWIK#150]
the form to set the new password uses for the first input field
"Kennwort"
and for the second input field
"Passwort wiederholen"

the second label should be
"Kennwort wiederholen"

**Comment by cbleek** [comment]
you can modify translations at 

https://www.transifex.com/yawik/yawik/

Modifications are not visible in realtime. But from time to time we import them.

**Comment by cbleek** [comment]
This was fixed in the meanwhile.

![auswahl_857](https://cloud.githubusercontent.com/assets/858642/12199815/4ee0afea-b61b-11e5-8cba-2ddc2796feef.png)
