### ISSUE TITLE
User menu not visible on small screen size

### ISSUE THREAD

**Issue by mbo-s** [cross-solution/YAWIK#152]
Go to http://yawik.org/demo/en resize the brwoser window and the User menu will not be visible, so a user can't login/register/logout
User menu visible:
![yawik-user-menu](https://cloud.githubusercontent.com/assets/9078194/9765111/da3fe834-5712-11e5-9152-41805f7a16f2.jpg)
After resizing / Mobile screen:
![yawik-where-is-the-user-menu](https://cloud.githubusercontent.com/assets/9078194/9765112/da53248a-5712-11e5-8de1-c7d25291250f.jpg)

**Comment by cbleek** [comment]
Yes, you're right. The login-info menu has to be shown.
