### ISSUE TITLE
Submit buttons not aligned

### ISSUE THREAD

**Issue by mbo-s** [cross-solution/YAWIK#153]
The submit buttons for the forms are not proper aligned, they should be under the form and not under the headline
e.g. http://yawik.org/demo/de/auth/forgot-password
http://yawik.org/demo/de/login?ref=%252Fde
![yawik-button-forgot](https://cloud.githubusercontent.com/assets/9078194/9820735/0e465f9c-58b6-11e5-9606-bc941a96c834.jpg)
![yawik-button-register](https://cloud.githubusercontent.com/assets/9078194/9820736/0e4e52a6-58b6-11e5-9327-3fc1fb8a56b6.jpg)

**Comment by cbleek** [comment]
the layout can be using css. The following less code was use to create the login on

http://www.karriere24.com

<pre>
// Login Box
#form-user-password-form,
#form-login-form {
    .form-content {
        animation: 1s ease-in-out 0.25s normal forwards 1 running reveal-banner;
        border-radius: 5px;
        background: rgba(52, 27, 43, 0.5) none repeat scroll 0 0;
        color: #fff;
        display: inline-block;
        opacity: 0.8;
        padding: 3em;
        a {
            color: #fff;
        }
        label {
            font-size: 85%;
        }
    }
}
</pre>

**Comment by mbo-s** [comment]
So I have to provide for every form additional css?
Why don't you use the correct bootstrap classes?
e.g.
http://getbootstrap.com/css/#forms-horizontal
the submit button is directly under the input fields, that is what I would expect
