### ISSUE TITLE
In application preview you can't submit your application

### ISSUE THREAD

**Issue by mbo-s** [cross-solution/YAWIK#154]
If you fill out the application form you can either abort, preview or send your application, in the preview you only can go back to the form or abort the application.
Here a user should be able to send the application

**Comment by cbleek** [comment]
all the logic of the submit button of an application you can find in:

https://github.com/cross-solution/YAWIK/blob/develop/module/Applications/view/applications/apply/_buttons.phtml

If you want to modify the logic quickly, you can overwrite the view in you module.conig.php.

The view script already contains a lot of conditions. If you have more time think about moving the logic into e.g. a view helper.
