### ISSUE TITLE
Parts of build.properties file are ignored when executing ./install.sh

### ISSUE THREAD

**Issue by blu-IT** [cross-solution/YAWIK#156]
Hello,

tried 2 or 3 times:

I have my preconfigured build.properties file, with these fields:

mongo.host=localhost
mongo.port=27017
mongo.db=Yawik
mongo.user=
mongo.pass=

username=test
password=test
email=me@e-mail.de

All these values (except email) are ignored when executing ./install.sh or /.phing.phar script.
The output at the end of the script:

generate-autoload-config:

 [echo] generate config files in: config/autoload
 [copy] Copying 8 files to /var/www/YAWIK/config/autoload
[filter:ReplaceTokens] No token defined for key "%%username%%"
[filter:ReplaceTokens] No token defined for key "%%password%%"
[filter:ReplaceTokens] No token defined for key "%%mongo.host%%"
[filter:ReplaceTokens] No token defined for key "%%mongo.port%%"
[filter:ReplaceTokens] No token defined for key "%%mongo.user%%"
[filter:ReplaceTokens] No token defined for key "%%mongo.pass%%"
[filter:ReplaceTokens] No token defined for key "%%mongo.db%%"

Trying with latest master from github (v0.20.1).

Regards

**Comment by cbleek** [comment]
Hi,

the build.properties mechanism was removed, since there is an install
module which asks you for the initial user and the database connection
string.

The module is executed, if there is no "yawik.config.global.php" within
the autoload directory.

So the install process looks now like this:

- checkout from github
- run composer install
- point your browser to the public directory.

If you download a package from sf.net, the composer dependencies are
already included. So you only have to untar/unzip the package and point
the browser to the "public" directory

Regards,

Carsten


Am 17.09.2015 um 09:41 schrieb blu-IT:
>
> Hello,
>
> tried 2 or 3 times:
>
> I have my preconfigured build.properties file, with these fields:
>
> mongo.host=localhost
> mongo.port=27017
> mongo.db=Yawik
> mongo.user=
> mongo.pass=
>
> username=test
> password=test
> email=me@e-mail.de <mailto:me@e-mail.de>
>
> All these values (except email) are ignored when executing
> ./install.sh or /.phing.phar script.
> The output at the end of the script:
>
> generate-autoload-config:
>
> [echo] generate config files in: config/autoload
> [copy] Copying 8 files to /var/www/YAWIK/config/autoload
> [filter:ReplaceTokens] No token defined for key "%%username%%"
> [filter:ReplaceTokens] No token defined for key "%%password%%"
> [filter:ReplaceTokens] No token defined for key "%%mongo.host%%"
> [filter:ReplaceTokens] No token defined for key "%%mongo.port%%"
> [filter:ReplaceTokens] No token defined for key "%%mongo.user%%"
> [filter:ReplaceTokens] No token defined for key "%%mongo.pass%%"
> [filter:ReplaceTokens] No token defined for key "%%mongo.db%%"
>
> Trying with latest master from github (v0.20.1).
>
> Regards
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cross-solution/YAWIK/issues/156>.
>


-- 
Cross Solution           | Carsten Bleek
Diemelstraße 2-4         | Tel: 069-71910361
60486 Frankfurt am Main  | Fax: 069-71910369
http://cross-solution.de | bleek@cross-solution.de

**Comment by blu-IT** [comment]
Hi Carsten,

what does "run composer install" mean? Run ./install.sh (like still mentioned in the documentation)?
When I do so, I get the message: 

no properties file found at build.properties. exit now.

Regards,
Ivan

**Comment by cbleek** [comment]
Hi Ivan,

so we've to update the docs.

You need to have the "composer" . If you have executed the install.sh
script, the composer was propably downloaded and is now located in your
YAWIK root as an executable file named "composer.phar"

Go into your YAWIK root and type

./composer.phar install

Reragrds,

Carsten

**Comment by blu-IT** [comment]
OK, so I think update of the docs is very essential now!

When I'm doing a fresh checkout from git (master), there is no ./composer.phar inside my YAWIK-root.
So I HAVE to run ./install.sh to get composer, but without a valid build.properties file this isn't possible. So I'm turning around again...

Regards,
Ivan

**Comment by cbleek** [comment]
Yes, you are right. I've created a new release, which should fix this problem.

I've also updated the docs:
http://yawik.readthedocs.org/en/latest/installation.html#setup-for-developers

**Comment by blu-IT** [comment]
Ok, thanks a lot for the effort!

Is there any reason for the remove of the build.properties mechanism? 
I was very happy with this solution, because auf the easy and nice way of giving some preset settings for a new installation, without having to configure things again and again...

**Comment by cbleek** [comment]
Am 18.09.15 um 21:22 schrieb blu-IT:
>
> Ok, thanks a lot for the effort!
>
> Is there any reason for the remove of the build.properties mechanism?
> I was very happy with this solution, because auf the easy and nice way
> of giving some preset settings for a new installation, without having
> to configure things again and again...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cross-solution/YAWIK/issues/156#issuecomment-141543894>.
>

1) the installation of YAWIK must be simple. It's now possible to
install it without a shell account.
2) we now use AbstractOptions to define default values. If you want to
modify the allowed mimetypes or the site of attachements of
applications, copy the
module/Applications/config/applications.forms.global.php.dist to the
aotoload directory, strip the ".dist" extension and adjust the options.
3) AbstactOptions gives us the possibility to make everything
configurable within the browser.

OK, you currently have to search the .dist files and have to manually
copy them. But if you have done it once, backup them and use it for
annother configuration.

**Comment by utrenkner** [comment]
It seems the build.properties are not yet completely removed from install.sh, thus resulting in an install error. Checking out release 0.22 and running install.sh I get:

[...]
YAWIK > load-properties-subtask:

     [echo] no module/Settings/config/build.properties found. Check for a .dist file
     [echo] module/Settings/build.xml not found
     [echo] Bundled: ${YAWIK.bundled} Module: Settings
 [property] Loading /usr/local/www/apache22/data/YAWIK/build.properties
 [property] Unable to find property file: /usr/local/www/apache22/data/YAWIK/build.properties... skipped
[...]

Nothing seems to have been installed/updated.

**Comment by blu-IT** [comment]
> It seems the build.properties are not yet completely removed from install.sh, thus resulting in an 
> install error.

I can confirm this.

**Comment by cbleek** [comment]
This was fixed in https://github.com/cross-solution/YAWIK/commit/b6ca658d97317f5c9853b8e2f9aa938e505171d4
