### ISSUE TITLE
Database not consistent when upgrading YAWIK

### ISSUE THREAD

**Issue by blu-IT** [cross-solution/YAWIK#157]
Hello,

for testing purposes I have two different instances of YAWIK running and working on the same database: 

1. v0.19.1-56 (which also created the originaldatabase)
2. v0.21-2

When browsing/using YAWIK v.0.21 I noticed now, that not all data/settings are recognized, for example my organizations or users are not shown any more. But the are still in my database.

Regards,
Ivan

**Comment by blu-IT** [comment]
Some additional information: 

Tested with 

`#`I.
1. v0.19.1-56 
2. v0.19-3
Both Versions working on the same database. 

`#`II.
1. v0.19.1-56 
2. v0.20.1
1. still worked on the database, 2. blank page with fresh setup/installation

`#`III.
1. v0.19.1-56 
2. v0.21-2
As mentioned above: Now BOTH versions don't show some informations (e.g. companys or received applications), while the information is still stored in the database.

**Comment by cbleek** [comment]
Hi Ivan,

sorry for the late answer. In 0.20 we've changed the paginator, which
enables YAWIK to use Search results from different resources like Mongo,
Solr, ES etc,...

The Database structure wasn't changed. Do you have Test Data?

Regards,

Carsten

**Comment by blu-IT** [comment]
Hi Carsten,

no problem, thanks for your reaction!

I can send you a dump (bson/json?) via e-mail, if you have some time to look at it?

Regards,
Ivan

**Comment by cbleek** [comment]
Hi Ivan,

please send your dump directly to bleek@yawik.org

Regards,

Carsten
