### ISSUE TITLE
Problems with 404 error

### ISSUE THREAD

**Issue by mbo-s** [cross-solution/YAWIK#162]
the Brand link point to different URLs:
1. http://yawik.org/demo/en/site-does-not-exist
"YAWIK DEMO" link points to http://yawik.org/demo/
2. http://yawik.org/demo/site-does-not-exist
"YAWIK DEMO" link points to http://yawik.org/demo/site-does-not-exist

Language change is broken
http://yawik.org/demo/en/site-does-not-exists

Here you can change the language
http://yawik.org/demo/site-does-not-exists

**Comment by cbleek** [comment]
This was fixed in f48f6719015cc8e477fa9a7d221c7f8c7c259304
