### ISSUE TITLE
IE submit buttons on step 2 broken/invisible

### ISSUE THREAD

**Issue by mbo-s** [cross-solution/YAWIK#163]
The submit buttons (back and next to preview) for adding a job offer are not visible on IE (tested with IE 11).

Steps to reproduce:
1. Use IE
2. go to http://yawik.org/demo/ and login
4. Add new job offer and go to step 2

![yawik-missing-buttons](https://cloud.githubusercontent.com/assets/9078194/10134743/5f431d60-65e8-11e5-97b5-b3f783a59b5e.jpg)

**Comment by mbo-s** [comment]
there is a problem with the footer-css, if i remove the whole footer from the layout you will see the buttons

**Comment by cbleek** [comment]
We close this issue. If the problem still exists, please reopen it
