### ISSUE TITLE
apply social login spinner button does not get removed

### ISSUE THREAD

**Issue by mbo-s** [cross-solution/YAWIK#164]
If you attach your social profil to an application the social buttton gets a spinner element.
If you complete the process (login, grant access ...) the spinner button will be removed.
If you click e.g. on facebook and close the popup the spinner button ist still visible

**Comment by cbleek** [comment]
I don't understand the problem.

If you click on attach my social profile, the spinning (css modification) is started by javascript. The spinning is stopped via javasript as soon as there is a positive response from the social network.

If the oAuth dialog is aborted by closing the authentication form of a social network, the positive response will never arrive and the spinning wheel will turn around forever.

**Comment by mbo-s** [comment]
And that is confusing. The spinning wheel indicates "Here happens something" but there happens nothing (in case of aborting)

**Comment by TiSiE** [comment]
We need to listen to the "popup closed" event (if possible) or periodically check if the popup is still open to be able to remove the spinning wheel.
