### ISSUE TITLE
attach social profiles not possible if loged in as admin

### ISSUE THREAD

**Issue by mbo-s** [cross-solution/YAWIK#167]
go to http://yawik.org/demo/en
login as admin
show own jobs and try to attach a social profile, you will see a 403 error
e.g. http://yawik.org/demo/en/apply/55c8ab17c5105cf750335e42

**Comment by cbleek** [comment]
Reason for this is located here 
https://github.com/cross-solution/YAWIK/blob/develop/module/Admin/config/module.config.php#L57

I'll remove the complete Admin module. It is not used at all.
