### ISSUE TITLE
Use always real popup for social logins

### ISSUE THREAD

**Issue by mbo-s** [cross-solution/YAWIK#169]
At the moment you only display the oauth dialog for attaching a profile in an application e.g. http://yawik.org/demo/en/apply/55c8ab17c5105cf750335e42

For the login or registering via social login the user gets redirected to the social platform.
e.g. https://www.facebook.com/dialog/oauth?[...]&display=popup
The Problem is that by using &display=popup the buttons for approving or aborting are optimized for a small window and not a normal browser window.

using oauth with &display=popup
![yawik-sociallogin](https://cloud.githubusercontent.com/assets/9078194/10161896/764a90e6-66a7-11e5-98a0-592b1a0dc050.jpg)
using oauth without &display=popup
![yawik-sociallogin-nopopup](https://cloud.githubusercontent.com/assets/9078194/10161898/77746910-66a7-11e5-9bba-023ca6b984a9.jpg)

**Comment by cbleek** [comment]
Hi,

the "display" behaviour can be configured at:

https://github.com/cross-solution/YAWIK/blob/develop/module/Auth/config/module.auth.global.php.dist#L9

I assume you have a config file like this in your autoload directory.

Regards,

Carsten

Am 29.09.2015 um 12:44 schrieb mbo-s:
>
> At the moment you only display the oauth dialog for attaching a
> profile in an application e.g.
> http://yawik.org/demo/en/apply/55c8ab17c5105cf750335e42
>
> For the login or registering via social login the user gets redirected
> to the social platform.
> e.g. https://www.facebook.com/dialog/oauth?[...]&display=popup
> <https://www.facebook.com/dialog/oauth?%5B...%5D&display=popup>
> The Problem is that by using &display=popup the buttons for approving
> or aborting are optimized for a small window and not a normal browser
> window.
>
> using oauth with &display=popup
> yawik-sociallogin
> <https://cloud.githubusercontent.com/assets/9078194/10161896/764a90e6-66a7-11e5-98a0-592b1a0dc050.jpg>
> using oauth without &display=popup
> yawik-sociallogin-nopopup
> <https://cloud.githubusercontent.com/assets/9078194/10161898/77746910-66a7-11e5-9bba-023ca6b984a9.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cross-solution/YAWIK/issues/169>.
>


-- 
Cross Solution           | Carsten Bleek
Diemelstraße 2-4         | Tel: 069-71910361
60486 Frankfurt am Main  | Fax: 069-71910369
http://cross-solution.de | bleek@cross-solution.de

**Comment by mbo-s** [comment]
That is right, but this is only active if a user attach in an apply, but not for login/register.

**Comment by mbo-s** [comment]
I have tested the settings with
<pre>
return array(
        'hybridauth' => array(
        "Facebook" => array (
            "enabled" => "true",
            "keys"    => array ( "id" => "ID", "secret" => "SECRET" ),
            "scope"   => "email,user_about_me,user_birthday,user_hometown,user_work_history,user_education_history",// optional
            "display" => "",
        ),
</pre>

Now for registering/login the window has the right size, but for attaching a profile it opens also in full size mode and then the user can't see everything.

**Comment by TiSiE** [comment]
The display mode should probably be passed as an additional parameter and not be set in the configuration. That will allow a more flexible usage.

**Comment by cbleek** [comment]
Die Facebook APIs haben sich alle geändert
