### ISSUE TITLE
Feature Wish: Individual rating of applications

### ISSUE THREAD

**Issue by Jeenias0815** [cross-solution/YAWIK#174]
* Currently, there seems to be an options to rate an application and it is showed in the applications overview with 0 up to 5 stars.
* Very often, several recruiters or team/departement leaders will read and rate the applications individually and afterwards talk with the others about the best rated ones.
* Therefore, it would be nice to be able to rate and comment the applications per recruiter or team/department leader. In the overview of applications, there could be shown the mean of all ratings.

**Comment by TiSiE** [comment]
That's exactly how it works since the rating feature were introduced.

If you have issues, please provide more detail what is not working as expected.
