### ISSUE TITLE
How to register as user/applicant ?

### ISSUE THREAD

**Issue by utrenkner** [cross-solution/YAWIK#182]
On the demo site you have an account for a demo applicant - but where could a real applicant register for such an account. Whereever I try, my default role is always recruiter - and even this should be made clear: Register as an applicant. Or: Register as a recruiter.

**Comment by cbleek** [comment]
This will set the hidden role field in the registration form to "user"
http://yawik.org/demo/de/auth/register/user

This will set the hidden role field in the registration form to "recruiter"
http://yawik.org/demo/de/auth/register/recruiter
