### ISSUE TITLE
No feedback on submitting search in jobboard if nothing is found

### ISSUE THREAD

**Issue by utrenkner** [cross-solution/YAWIK#183]
When I search the jobboard, and no suitable job is found, I get zero feedback. Thus, the user does not know whether the search is still taking place or whether no job was found.

My preference would be to show a result such as "Your search showed no result" or similar.

Alternatively, there could be a feedback in the sense of e.g. a spinning wheel, indicating that the search is still ongoing (or not).

**Comment by TiSiE** [comment]
Why not do both! :)

**Comment by utrenkner** [comment]
@TiSiE You are absolutely right: Both would even be better...

**Comment by TiSiE** [comment]
There is now a loading indicator and a "nothing here" notice for pagination-containers.

Read the doc: http://yawik.readthedocs.org/en/latest/modules/core/pagination/views.html
