### ISSUE TITLE
Notifcations: stick / close not needed for trivial notifications

### ISSUE THREAD

**Issue by utrenkner** [cross-solution/YAWIK#184]
I do not yet see the reason for having to chose if I want to close a notification or if I want to make it "stick". I assume it is meant for longer / more complex notifications, which I want to review or possibly even note.

But for trivial notifications they are just a nuisance (and a usability problem): E.g. when I log in, the notification overlays the top right of the navigation with the user setting. I manually have to close the notification to edit my profile etc. But in my tests it sometimes took me three attempts to close it, because the two options are way too close together.

My preference: Completely remove the "stick" option for trivial notification (especially positive ones!). I would even remove the "close" option for most notifications. It is enough that it showed up for a short time.

If the two options stick and close are needed, then they should be farther apart to make clicking the intended one easier (I have not even tried how this would work in a smartphone).

**Comment by utrenkner** [comment]
Related to the issues above: On a large screen one can easily overlook the notification in the top-right corner. For example, when I register or change the password, my focus is in the centre or even the left side of the screen. It would be great if the notification could appear close to where the focus of attention was at this moment.

**Comment by TiSiE** [comment]
I'm totally with you! 

Notifications will definitely get an overhaul.
