### ISSUE TITLE
active / inactive filter broken?

### ISSUE THREAD

**Issue by utrenkner** [cross-solution/YAWIK#185]
In my test jobboard I have one job - but logged-in as administrator, I cannot see it through the "overview" table. Whatever search and filter settings I use, this job never shows up.

A possibly related problem can be seen in the official YAWIK demo. Logging in as "demo" (admin), I can currently see 11 jobs under https://yawik.org/demo/en/jobboard. This is also, what I see under "overview" with the filter set to "all". When I toggle the filter to "active", I only see 9, when I toggle it to "inactive" I see none. Thus, we have: 11 jobs in the jobboard (presumably all of them active?), 9 "active", none "inactive".

**Comment by cbleek** [comment]
The "overview" list shows jobs of an own company. If "my jobs" is selected, jobs are listed, which were entered by the user. If "all jobs" ist selected, the jobs entered by cp-workers are listed to.

The "jobboard" list currently reduces the list of jobs to those which are related to the logged in user. This is a bug, which will be fixed soon.

**Comment by cbleek** [comment]
this was fixed
