### ISSUE TITLE
Validation of mongo connection string seems to be broken

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#186]
Userfeedback:

von der Demo zu Yawik bin ich sehr begeistert, aber über einer MongoDB bei mongolab.com kann es anscheinend entgegen den Anweisungen aus den Docs nicht installiert werden. Wenn ich bei der Installation von Yawik einen „Datebase connection string“ in der Form von mongodb://nutzername:passwort@subdomain.mongolab.com:35014/datenbank eingebe, erscheint bei Yawik unter dem Eingabefeld folgende Fehlermeldung: „Invalid connection string“.

Was könnte man dagegen machen? Sobald man den Doppelpunkt zwischen nutzername und passwort entfernt, verschwindet die Fehlermeldung, aber dann sind die Anmeldedaten nicht mehr korrekt. In der Datei YAWIK-0.23.3/module/Install/src/Validator/MongoDbConnectionString.php scheint das geregelt zu werden. Ich habe bereits versucht Zeile 49 anzupassen, leider ohne Erfolg.

**Comment by TiSiE** [comment]
The regular expression used to validate the connection string does not work as expected.
