### ISSUE TITLE
Ajax request runs into a loop, if the session is expired.

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#190]
If you click on the next button of a paginator  with an expired session, the ajax request runs into a loop.

**Comment by TiSiE** [comment]
For pagination that uses the rewritten TextSearchForm and pagination-container javascript, this behaviour cannot be reproduced. So it seems once all pagination-able content is converted, this bug will be fixed.

Therefor this ticket will be closed!

Relevant commits:
 d0914a4, b21b641, b57d28e
