### ISSUE TITLE
Deprecated: ServiceManagerAwareInterface is deprecated and will be removed in version 3.0

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#192]
If we update the composer dependencies to the latest Version, we get:

Deprecated: ServiceManagerAwareInterface is deprecated and will be removed in version 3.0, along with the ServiceManagerAwareInitializer. Please update your class Auth\Listener\AuthAggregateListener to remove the implementation, and start injecting your dependencies via factory instead

**Comment by utrenkner** [comment]
I assume this means for existing YAWIK users: Don't touch composer at the moment?

Do you know exactly which update is responsible for this deprecation? Could we lock the version of that particular composer package and update just the rest?

Is a major rewrite of YAWIK necessary to bring it  in sync with the version of ZF2? When do you expect to publish v0.25?

**Comment by cbleek** [comment]
Hi,

that means, if you run "composer update", which updates all external 
dependencies, YAWIK will break. You can always run "composer install" 
which installs all the versions, which are locked in the composer.lock file.

It's not a big issue. We'll have to adopt 3 Listener classes in the Core 
module. We've already started a local feature branch.

Regards,

carsten

Am 14.03.16 um 15:10 schrieb Uwe Trenkner:
>
> I assume this means for existing YAWIK users: Don't touch composer at 
> the moment?
>
> Do you know exactly which update is responsible for this deprecation? 
> Could we lock the version of that particular composer package and 
> update just the rest?
>
> Is a major rewrite of YAWIK necessary to bring it in sync with the 
> version of ZF2? When do you expect to publish v0.25?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cross-solution/YAWIK/issues/192#issuecomment-196323789>.
>


-- 
Cross Solution           | Carsten Bleek
Diemelstraße 2-4         | Tel: 069-71910361
60486 Frankfurt am Main  | Fax: 069-71910369
http://cross-solution.de | bleek@cross-solution.de
