### ISSUE TITLE
What about ZF2-AcMailer

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#194]
What do you think of AcMailer. Should we use it in favour our own Mailservice Classes?

https://github.com/acelaya/ZF2-AcMailer

**Comment by utrenkner** [comment]
I cannot judge the quality of this module. But it has been around for some time, seems to be actively developed and - according to packagist.org - has over 17,000 installs.

Generally, I tend to think that using such standard solutions is a very good idea, rather then (re-)implementing the same functionality over and over again.

For us it would be very interesting, when we want to add attachments in certain mails. Currently it is not possible to easily switch between text and mime mails (both are used within YAWIK).
