### ISSUE TITLE
TemplateValueHydrator::ectract gets job object

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#197]
I've described how to add an additional elemet to job posting template in https://groups.google.com/d/msg/yawik/os6SC_SaOzw/GBdVBbBuAwAJ

I've noticed, that our TemplateValueHydrator::ectract method can gets a job object, which leads to an error.
Checking the instance is a short fix, but the bug is probably somewhere else

https://github.com/cross-solution/YAWIK/blob/develop/module/Jobs/src/Jobs/Entity/Hydrator/TemplateValuesHydrator.php#L78

**Comment by TiSiE** [comment]
This currently only affects optional modules. We need to refactor the addition of custom template values, but will address this in a separate issue.
