### ISSUE TITLE
Auth/public/js/form.socialprofiles.js displays wrong profile data

### ISSUE THREAD

**Issue by fedys** [cross-solution/YAWIK#199]
socialprofiles.js sends wrong data to http://yawik.local/en/applications/null?action=social-profile&network={network} for subsequent clicks on "view profile data" links (without reloading the page).

Possible solutions: replace bootstrap's $modal remote option (deprecated since v3.3.0) with regular jQuery $.post() method

**Comment by fedys** [comment]
Can I fix it?

**Comment by cbleek** [comment]
Yes, please do so

**Comment by fedys** [comment]
Fixed in **issue-199** branch
