### ISSUE TITLE
Exception on job creation

### ISSUE THREAD

**Issue by fedys** [cross-solution/YAWIK#202]
If user has no organization at all and tries to create new job then he gets "Sorry, you may not create jobs." message as expected.

If user has only draft organization and tries to create new job on http://yawik.local/en/jobs/edit then he gets  HTTP 500.

**Comment by mbo-s** [comment]
it looks like issue #151

**Comment by fedys** [comment]
You are absolutely right. Sorry for duplication.
Dne 26. 4. 2016 1:24 odpoledne napsal uživatel "mbo-s" <
notifications@github.com>:

**Comment by cbleek** [comment]
@fedys : please fix this

**Comment by cbleek** [comment]
This was fixed by @fedys
