### ISSUE TITLE
preview feature of an applications requires authentication.

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#204]
since 62765cc a user cannot preview it's application anymore.

**Comment by cbleek** [comment]
I referenced the wrong issue in the commit message.

https://github.com/cross-solution/YAWIK/commit/465be711242ffb80282d2e07b7809d5826daa06b fixes this issue.

@TiSiE : please review

**Comment by TiSiE** [comment]
Well done! ;)
