### ISSUE TITLE
Adding users to group does not work

### ISSUE THREAD

**Issue by fedys** [cross-solution/YAWIK#209]
I am not sure how this feature should work but it looks like a bug. If I want to add some user to just created group on http://yawik.org/demo/en/my/groups/new I see no search results in modal even if http://yawik.org/demo/en/my/groups/search-users (+ POST['query'] = 'e') returns JSON with two objects

**Comment by cbleek** [comment]
The groups feature is currently hidden. We'll fix this later

**Comment by TiSiE** [comment]
Furthermore, the user group feature is deprecated and was replaced with Organization Employees Management.
