### ISSUE TITLE
Unable to activate Job Ad

### ISSUE THREAD

**Issue by flashguy22** [cross-solution/YAWIK#212]
Hi,

after setting up a job ad as a recruiter and then logging in as admin I can't activate the job.
When I click on the little pencil icon next to the job I get the following error:

`Zend\View\Renderer\PhpRenderer::render: Unable to render template "px-skin/manage/approval"; resolver could not resolve to a file`

This is really weird because I have no template called px-skin. My custom template is called PxSkin.
px-skin might come from an early try with making a custom template.

Any Ideas on how I can change and fix this?

**Comment by TiSiE** [comment]
The ZF2 registers some listeners in the dispatch process and one of them sets up a view model and inject a template if the controller does not return a view model (but an array instead). The logic to determine the template used is to take the dispatched Module controller and action and transform it to a template. CamelCased words are transformed to dash-separated words, thus "PxSkin" is transformed to "px-skin".

It seems that you have overwritten the ManageController of the jobs module. Its approval action only returns an array, and so the ZF2 listener injects the template "px-skin/manage/approval".

There are two solutions:

1. Let the controller action return a view model with the proper template injected.

2. Define a template "px-skin/manage/approval" which points to the appropriate template ("jobs/manage/approval") in the ["view_manager"]["template_map"] entry of the module.config of your module.

**Comment by flashguy22** [comment]
Thank you very much for this tip!
I had following code in my module.config.php which I removed and now it works
` /**
              * override the Jobs/Manage to inject the additional classification form into the view.
              */
             'controllers' => array(
                 'factories' => [
                     'Jobs/Manage' => 'PxSkin\Factory\Controller\ManageControllerFactory',
                 ]
             ),`

Strange because I already had an active job ad which we probably activated before implementing the custom template.

**Comment by TiSiE** [comment]
You're welcome. I'm glad it is working for you now.
