### ISSUE TITLE
Apply link not working after update

### ISSUE THREAD

**Issue by flashguy22** [cross-solution/YAWIK#213]
I just updated Yawik to the latest sources from the git repository and now the apply link doesn't work anymore. It links to the job offering and not the apply site.
`<a href="<?php echo $this->uriApply ?>" class="button special" target="_blank">Jetzt bewerben</a></p>`

Rolling back to the last version doesn't work as I get redirected to the error Page. 
Any quick fix for this as we have job offerings live?

http://bewerbung.phoenixdesign.com/

Edit: I was able to revert as I had the mongodump and now it's working with the old version. Still in need of an explanation on howto use the latest code as we need to use the new workflow.

**Comment by cbleek** [comment]
Please use

<?=$this->jobApplyButtons($this->applyData)?>

But I'll take a look, if we can make the "uriApply" variable available 
again. So old Templates work without modifications.

Regards

**Comment by cbleek** [comment]
The variable will be back in 0.25.

Thanks for reporting
