### ISSUE TITLE
Applicants can create CVs

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#214]
The current CV form http://yawik.org/demo/de/cvs/create (login as applicant/applicant) has to be fixed. 

1) The Cv Entity should get a contact subcollection (as we have done for applications). The contact data should be prefilled with the users $user->getInfo() data.

If the users starts entering the cv it should look like:

![eingabe-lebenslauf-start](https://cloud.githubusercontent.com/assets/858642/15420950/37f16efa-1e71-11e6-8162-152d20908fea.png)

By clicking on the icon or button, the relevant form should appear. This might look like this

![eingabe-lebenslauf-add-education](https://cloud.githubusercontent.com/assets/858642/15421200/3272ac0e-1e72-11e6-8955-c098cb21a260.png)

The form is saved and the entered data is shown in display mode.

**Comment by fedys** [comment]
The first implementation is in the issue-214 branch.
Following issues are not solved:

1. Form elements as a DateSelect are not initialized by JS if are added by clicking the "+" link button
2. There is no way to clear a collection (except some ugly hack) using zend-form 2.6.x. The package zend-form has to be updated minimally to zend-form 2.7.x (I tested zend-form 2.8.3 with success)
3. The Core\Form\View\Helper\FormCollection does not render a "-" link button properly if a collection contains nested collections

**Comment by cbleek** [comment]
I've fixed the version of zend-form to 2.6 , because of #192

**Comment by TiSiE** [comment]
@cbleek and me decided, that as a matter of consistency (look and feel and usability) we want following behaviour:

* Collections are separated into dedicated forms to allow editing one single entry independent from the others.

* The "Add" button should be below the last form of a collection. The "Delete" button should be in the upper right corner of an entry form (summary view) to the right of the "edit" button.

---

As an idea: What we need is a kind of dynamic [form container](https://github.com/cross-solution/YAWIK/blob/cbf82c376ae60ee7c0e61221deb4a49d2e5069ca/module/Core/src/Core/Form/Container.php) that allows adding new forms to it via javascript (analogically to the  form collections with fieldsets.) 
I don't know if it's possible to extend from ZF's form collection... (for reuse).
Another thing to consider is hydrating of the entitys' sub collection.. we will need a new Hydrator for that, i think.

**Comment by fedys** [comment]
OK, I will create a new form container allowing functionality described above. I will place it into Core package without affecting the current implementation of the form container.
