### ISSUE TITLE
Apply Form Error in 0.25

### ISSUE THREAD

**Issue by flashguy22** [cross-solution/YAWIK#215]
I updated our yawik instance to release/0.25 and with the new fix the `uriApply ` is available and working again.

Unfortunately I get following error on the Apply Form Page:

`Ein Fehler ist aufgetreten
An error occurred during execution; please try again later.
Zusätzliche Informationen:
Zend\Form\Exception\InvalidElementException
Datei:
/opt/yawik/vendor/zendframework/zend-form/src/Fieldset.php:218
Nachricht:
No element by the name of [profiles] found in form
Stapelverlauf:
#0 /opt/yawik/module/Core/src/Core/Form/Container.php(630): Zend\Form\Fieldset->get('profiles')
#1 /opt/yawik/module/Applications/src/Applications/Controller/ApplyController.php(199): Core\Form\Container->get('profiles')
#2 /opt/yawik/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Applications\Controller\ApplyController->indexAction()
#3 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#4 /opt/yawik/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#5 /opt/yawik/vendor/zendframework/zend-eventmanager/src/EventManager.php(214): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#6 /opt/yawik/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#7 /opt/yawik/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#8 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#9 /opt/yawik/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#10 /opt/yawik/vendor/zendframework/zend-eventmanager/src/EventManager.php(214): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /opt/yawik/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 /opt/yawik/public/index.php(49): Zend\Mvc\Application->run()
#13 {main}`

The same error as here: http://yawik.org/demo/en/apply/564e0bbb4e197fa4260db070

**Comment by cbleek** [comment]
Social Profiles are deactivated for the demo user in the demo.

![auswahl_981](https://cloud.githubusercontent.com/assets/858642/15423270/ed8bccaa-1e7c-11e6-814c-67820b5b188b.png)

This currently leads the the Problem, that the application form cannot be displayed at all. Will fix that.

Do you have deactivated social profiles in your environment, too?

**Comment by TiSiE** [comment]
This happens, if the Social Profiles Buttons are deactivated for a job offer.

**Comment by flashguy22** [comment]
We are not using social Profiles in our setup.
