### ISSUE TITLE
"guests" cannot access the api anymore

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#216]
Hab's schon gefunden: Der Eintrag muss 'Jobs/ApiJobListByOrganization' heissen.

VG,
Jochen

Am Dienstag, 24. Mai 2016 09:43:59 UTC+2 schrieb joche...@jobvector.com:

    Hallo Carsten,

    der Zugriff auf die Jobliste unter /de/api/jobs/organization/organisationID funktioniert nur nach einem Login (in einer älteren Version ging das imho auch ohne Login?) und ist somit nicht mehr von einer externen Seite her aufrufbar. Der ACL-Eintrag 'Jobs/ApiJobList'' in die Jobs/module.config.php:

       .....
               'guest' => array(
                    'allow' => array(
                        'Jobboard',
                        'Jobs/Jobboard',
                        'Jobs/ApiJobList',
                        'Jobs/Template' => [ 'view', 'edittemplate' ],
                        'Jobs/Manage' => array(
                            'template',
                        ),
                        'route/lang/jobs/template',
                        'route/lang/jobboard',
                    ),
                    'deny' => 'JobList'
       ......

    ändert daran nichts...

    Wo kann ich den Zugriff den für 'guest' freischalten?

    VG,
    Jochen

**Comment by TiSiE** [comment]
Currently there is a route "de/api/jobs" configured which point to a non-existent controller "Jobs/ApiJobList". However the organization api now works for non-authenticated users.

[router.config.php #27-35](https://github.com/cross-solution/YAWIK/blob/5f2313fc4866a86c3d0a37dd865ccb3caa38f8cb/module/Jobs/config/router.config.php#L27-L35)
