### ISSUE TITLE
Mails not sent

### ISSUE THREAD

**Issue by cjriks** [cross-solution/YAWIK#219]
Status:
- Job is attached to the admin user
- in Settings -> E-Mail Notifications: all checkboxes are on
- a guest user fills out the apply form: "sent copy" is checked

After submitting the form the automatic notification is send to the applicant but no copy of the submitted data, no BCC email and no email about the new application are sent.

**Comment by TiSiE** [comment]
Which version of YAWIK does this affect?

Maybe it's because of the issue #222, which was introduced with commit f6e11db (and affects the current develop version.

**Comment by cjriks** [comment]
Affected is the actual develop version

**Comment by TiSiE** [comment]
will be handled in #222
