### ISSUE TITLE
Adding new User forbidden

### ISSUE THREAD

**Issue by flashguy22** [cross-solution/YAWIK#220]
I just tried to invite another colleague to our yawik but get forbidden as error. We have ten active users already. Is there a limit? Or does it have to do with the update to 0.25?

**Comment by TiSiE** [comment]
Please provide more information about the steps to reproduce this behaviour.

There is definitely no user limit. 

Did you get the forbidden error while inviting or did the invited user get the forbidden error while trying to accept the invitation?

**Comment by flashguy22** [comment]
I got the forbidden message while inviting a new user to the company as Admin.

**Comment by cbleek** [comment]
The bug is in the develop too
![auswahl_999 013](https://cloud.githubusercontent.com/assets/858642/15930890/76371bd0-2e55-11e6-890c-816f79a9dd45.png)

**Comment by TiSiE** [comment]
This is fixed now in v0.25.1
