### ISSUE TITLE
HTMLTemplateMail is broken due to Zend Mvc Upgrade

### ISSUE THREAD

**Issue by TiSiE** [cross-solution/YAWIK#222]
`Call to undefined method Zend\Mvc\View\Http\ViewManager::getResolver() (errno 1) in /YAWIK/module/Core/src/Core/Mail/HTMLTemplateMessage.php on line 238
`
zend-mvc removed the method getResolver() from the ViewManager, which unfortunately is used in the HTMLTemplateMail.

**Comment by kilip** [comment]
This issue should be fix in   a1740234d6d7a7e08587c371a4008aafb6dbf646 commit, I leave a comment here:

https://github.com/cross-solution/YAWIK/commit/a1740234d6d7a7e08587c371a4008aafb6dbf646#commitcomment-17854789

**Comment by cbleek** [comment]
Iv've merged the commit yesterday. Didn't know that it fixes this issue. Demo System sends mails again. So we can close this issue

Thanks for reviewing.
