### ISSUE TITLE
Subsequent filing of documents

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#231]
It should be possible for an applicant to add documents to his resume, after submission. 

Original Feature request:

>   - Bewerbungsvorschau müsste vor dem Versand als Pflicht hinterlegt sein
>  - oder es sollte sofort eine Fehlermeldung auftauchen, wenn die Datei nicht
>    hochgeladen werden kann
>  - Möglichkeit schaffen, nochmals auf die Bewerbung zuzugreifen, damit man
>    Dateien nachschieben kann, denn oft erhalten Bewerber ihre Zeugnisse erst
>    nachdem sie sich beworben haben - diese müssen dann per Mail nachgereicht
>    werden und Admin hat keine Möglichkeit, die Dateien hinzuzufügen, so müssen
>    wir aktuell immer 2-gleisig fahren
> 
>  - sind bestimmte Dateiformate ausgeschlossen oder ungünstig?

**Comment by PrithiN** [comment]
Hello Mr. Bleek,

Could you please tell us how to do this?
Do I need the link I get after sending the application?

**Comment by cbleek** [comment]
Currently a user can't modify his application after submitting. This issue was created to create this feature. Feel free to describe the way it should work.

**Comment by TiSiE** [comment]
We decided to add a module option to allow the de-/activation of subsequent file uploads.
If this option is enabled, the APPLICANT will get the FILE UPLOAD form rendered on the detail page (unless the format is pdf, obviously).

@fedys: Please implement this.

**Comment by fedys** [comment]
Okay, I will render an upload form on the [detail page](https://yawik.org/demo/en/applications/57cd1a484e197f54670930f1) in the _Attachments_ box. The upload form will be implemented the same way as on the [apply page](https://yawik.org/demo/en/apply/5667efdb4e197fe6037b246e). Is it right?

**Comment by cbleek** [comment]
We'll need a new form. Mathias with describe you how it should look like

**Comment by TiSiE** [comment]
![subsequent-file-upload](https://cloud.githubusercontent.com/assets/2029304/18248919/7e6a6242-737b-11e6-96bf-74b3be71fc0e.png)

* The social profiles, if attached SHOULD be rendered above the file upload element and below the file list.
* Uploaded files SHOULD be added to the list.
* Deletion SHOULD NOT be allowed
