### ISSUE TITLE
add preview link to the acknowledment mail

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#232]
Original reture Request:

> "wird momentan nur kurz angezeigt, nachdem man sich beworben hat;
> wenn sich der Bewerber den Link nicht 
> aktiv abspeichert, geht er verloren"

> " - der Link sollte in einer separaten Mail an den Bewerber gesandt werden
>  - besser, wenn er in der Eingangsbestätigungsmail erscheinen würde
> "

**Comment by TiSiE** [comment]
Translation:

[The preview link of an application] is shown only in the browser after submitting an application successfully. If not actively saved, it is lost. Therefor this link should be send in a separate mail or - even better - should be included in the confirmation mail.

**Comment by cbleek** [comment]
The link should be included in the confirmation mail

**Comment by cbleek** [comment]
kilip has currently no time. @fedys , can you do this?

**Comment by fedys** [comment]
@cbleek Yes, I can.


Dne 2.9.2016 v 13:40 Carsten Bleek napsal(a):
