### ISSUE TITLE
make entities searchable by solr

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#234]
create a new module named "Solr". The module should hook into the doctrine update and send the entity data to a solr server.
In addition, if a search is performed, it should provide a paginator, which searches the solr server

@TiSiE : can you add som technical details, please?

**Comment by TiSiE** [comment]
Doctrine provides its [own event system](http://doctrine-orm.readthedocs.io/projects/doctrine-mongodb-odm/en/latest/reference/events.html#lifecycle-events).
Examples in YAWIK are:
[Applications\Repository\Event\JobReferencesUpdateListener.php](https://github.com/cross-solution/YAWIK/blob/develop/module/Applications/src/Applications/Repository/Event/JobReferencesUpdateListener.php) which is registered in the [Application/config/module.config.php](https://github.com/cross-solution/YAWIK/blob/develop/module/Applications/config/module.config.php#L29) around line 29.

---

For the second part of this feature I see two possible solutions:

1. Replace the Paginator service in the service manager config with the Solr enabled Paginator
2. The [CreatePaginator](https://github.com/cross-solution/YAWIK/blob/develop/module/Core/src/Core/Controller/Plugin/CreatePaginator.php) plugin triggers a "fetch paginator" event and if a paginator is returned by a registered listener, it will be used.

The first approach is probably fairly easy to implement, but it's very unflexible.

The second approach is more complicate to implement but allows a lot of flexible afterwards like
* Return different paginators based upon the search criterias (assuming the search parameters are provided in the triggered event).
* Maybe just return a paginator service name and let the plugin do the rest of the work.
* Use of priorities to allow other modules to provide a custom/extended paginator INDEPENDANT of the module loading order.

In case the second approach is chosen, creating event managers and attaching listeners can be made nearly exclusivly in the configuration files.

Unfortunately, there is only inline documentation available, which describes the way event managers and listener attaching should be done in YAWIK:

[Core\Factory\EventManager\EventManagerAbstractFactory](https://github.com/cross-solution/YAWIK/blob/develop/module/Core/src/Core/Factory/EventManager/EventManagerAbstractFactory.php)

some example configration:
[Jobs/module.config.php](https://github.com/cross-solution/YAWIK/blob/develop/module/Jobs/config/module.config.php#L217)
[Orders/module.config.php](https://github.com/cross-solution/YAWIK/blob/develop/module/Orders/config/module.config.php#L43)

Getting event managers from the abstract factory:
[Orders\Factory\Form\JobInvoiceAddressFactory](https://github.com/cross-solution/YAWIK/blob/develop/module/Orders/src/Factory/Form/JobInvoiceAddressFactory.php#L44)
