### ISSUE TITLE
solr update fails when using the german language

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#247]
If I use the german language, I can see the following error in the solr log, while updating a job.

It seems, that the latitude 8.612 and longitude 50.2265 is converted to the german format 8,612 50,2265, which results to the error below. Using the english language, updates are running fine.

2016-07-06 12:05:11.869 ERROR (qtp110456297-16) [   x:YawikJobs] o.a.s.h.RequestHandlerBase org.apache.solr.common.SolrException: Unable to parse shape given formats "lat,lon", "x y" or as WKT because java.text.ParseException: Unknown Shape definition [8,612,50,2265]

**Comment by kilip** [comment]
Hello @cbleek,

Unfortunately I can't reproduce this bug in my local machine. I already tried using German language but ```$location->getCoordinates()->getCoordinates()``` still using ```.``` decimal separator.

I hope this line of code can fix this bug:
```php
// module/Solr/src/Solr/Listener/JobEventSubscriber line #178
$coordinates = $location->getCoordinates()->getCoordinates();
$coordinate = doubleval($coordinates[0]).'%'.doubleval($coordinates[1]);
$coordinate = strtr($coordinate,[
                '%'=>',',
                ','=>'.'
]);
$document->addField('latLon',$coordinate);
```
