### ISSUE TITLE
Error during creating a Cv entity

### ISSUE THREAD

**Issue by fedys** [cross-solution/YAWIK#260]
I get the following error on /en/my/cv if a [Cv entity is just created](https://github.com/cross-solution/YAWIK/blob/develop/module/Cv/src/Cv/Controller/ManageController.php#L61):

`ERR Argument 1 passed to Doctrine\ODM\MongoDB\Persisters\PersistenceBuilder::prepareAssociatedCollectionValue() must be an instance of Doctrine\ODM\MongoDB\PersistentCollection, instance of Core\Entity\Collection\ArrayCollection
`

I found [this line](https://github.com/cross-solution/YAWIK/blob/develop/module/Cv/src/Cv/Entity/Cv.php#L141) causes the error. See the commit ce5fb55dcc4a3c6424946c761bf10ca6f9c0756b

**Comment by TiSiE** [comment]
I cannot reproduce this behaviour. It's working as expected.

The error message you get is clearly not associated with the setting of the user and the updating of the permissions.

Please make sure that your database is in a clean state and then try to reproduce this error
(Especially clear all Cvs associated to the user you're testing with)

**Comment by fedys** [comment]
@TiSiE I try to reproduce it with another user (with the same role) with no success. The error does not occur :). Sorry for that.
