### ISSUE TITLE
Invalid redirect after social login from URL not containing a language part

### ISSUE THREAD

**Issue by fedys** [cross-solution/YAWIK#263]
Example:
I am on http://yawik.local/logout then click on the Facebook button and resulting URL is http://yawik.local/engout#_=_ which does not exist.

This issue is only related to environments with empty basePath. https://yawik.org/demo/logout is okay.

**Comment by TiSiE** [comment]
How did you get to /logout ? There is just one link in YAWIK that leads you to /logout, and there will be a redirect to the startpage afterwards....

**Comment by TiSiE** [comment]
However, the behaviour is caused in [Auth/IndexController#L248](https://github.com/cross-solution/YAWIK/blob/f8d06d67db6a3172ef25583cf17c999f8e24d45d/module/Auth/src/Auth/Controller/IndexController.php#L248).
