### ISSUE TITLE
Prevent recruiters to make cvs public

### ISSUE THREAD

**Issue by TiSiE** [cross-solution/YAWIK#266]
Recruiters are able to "convert" an application to a cv "Talent-Pool". But for privacy reasons of the applicant, this cv should not be allowed to be public.

We will think of a workflow to allow it somewhere in the future, but as we're working forward to 0.26, we simply disallow it for now.

**Comment by cbleek** [comment]
was done in: https://github.com/cross-solution/YAWIK/commit/916406cc80b52811c17d9e1fcf33502375bb3b70
