### ISSUE TITLE
Exceptions thrown on invalid URL parameters

### ISSUE THREAD

**Issue by fedys** [cross-solution/YAWIK#276]
If you enter an invalid URL parameter then exception is thrown. An HTTP 404 should be shown instead. Plus some meaningful message could be displayed.

Some URL examples:
https://yawik.org/demo/en/jobs/edit?id=5667efdb4e197fe6037b246w
https://yawik.org/demo/en/organizations/edit/5733102a4e197f7d55cb9103
https://yawik.org/demo/en/settings/Ordersa

**Comment by cbleek** [comment]
good idea. Please make it right.

**Comment by TiSiE** [comment]
Done with 880247e
