### ISSUE TITLE
Core/js/forms.file-upload.js relies on action attribute set by Core\Form\Container

### ISSUE THREAD

**Issue by fedys** [cross-solution/YAWIK#281]
If an [upload form](https://github.com/cross-solution/YAWIK/blob/develop/module/Core/src/Core/Form/FileUploadFactory.php)  is used standalone (without being composed into a Core\Form\Container) then JS validation does not work properly because the [forms.file-upload.js](https://github.com/cross-solution/YAWIK/blob/develop/module/Core/public/js/forms.file-upload.js#L173) assumes a form with an attribute `action="?form=name"` set.

**Comment by TiSiE** [comment]
Additionally, I guess it will also fail, if the FileUpload form is in a nested container (which means, the action attribute will be something like "parentContainer.actualForm").

In that case, the errors will be stored like 
``` json
{
    "errors": {
         "parentContainer":  {
            "actualForm": {
                "errorKey": "message"
            }
        }
    }
}
```

So we need two things:
- Handle dot separated form names   
  (I do not have an idea on this one)
- A mechanism to provide the form name, if the action attribute is not in the assumed format.   
   This could be done by using a "data-errorkey" attribute. If defined, its value will be used, if not, it is assumed, the action attribute is "well formatted".
