### ISSUE TITLE
Email forwarding notifications don't work properly

### ISSUE THREAD

**Issue by julian3005** [cross-solution/YAWIK#283]
When forwarding certain applications nothing happens. No error message gets displayed and no Email gets sent. Other applications can be forwarded but sometimes there is also no message saying that it succeeded.

**Comment by cbleek** [comment]
is there is something in the YAWIK/log/error.log ?

**Comment by julian3005** [comment]
Nothing related to that.

**Comment by TiSiE** [comment]
From the current informations, it is hard to reproduce the behaviour.
It would help a lot, if you could provide more informations
Especially what is the difference between "working" applications and those, where the emails are not send. 

* Different states?
* Associated job belongs to an hiring organization?
* Which recruiter is associated to the job (and therefor to the application)  
   Differ these users?

**Comment by julian3005** [comment]
The state is confirmed and all jobs are for the same organization.
All jobs have been assigned to the same recruiter. 
I could't find out exactly what the difference between working aplications and those who don't but
there is an application with an 7 MB PDF attached and the mail does not get sent out and there is no message/notification saying error or success. ( We have set attachmentsMaxSize in 'Yawik\module\Applications\src\Applications\Options\ModuleOptions.php'  to 15728640 and we have also set attachmentsMaxSize in 'Yawik\config\autoload\applications.forms.global.php' to 15728640).
Is it maybe because we have missed to change a value?
But that still does not explain why there are no error or success notifications like there used to be in previous versions.

**Comment by TiSiE** [comment]
I'll check if the attachments could cause the issue.

**Comment by julian3005** [comment]
After updating from v0.26 to v0.29 the notifications work again, but applications with about 8 MB of attachments or bigger still fail to forward. 
![erroryawik](https://cloud.githubusercontent.com/assets/22173482/26359674/5e652e14-3fd6-11e7-84b0-e7e1b97f31b1.jpg)

**Comment by cbleek** [comment]
the default memory limit for post requests in PHP is 8MB. You have to 
increase it, in case you want to allow attachments larger attachments. 
You also have to adjust the upload_max_filesize in you php.ini

; http://php.net/post-max-size
post_max_size = 8M
; http://php.net/upload-max-filesize
upload_max_filesize = 2M

**Comment by julian3005** [comment]
We did increase both to 15M

![erroryawik3](https://cloud.githubusercontent.com/assets/22173482/26361686/ffdec07a-3fdb-11e7-87d2-12b36ca7710a.jpg)

**Comment by TiSiE** [comment]
I believe strongly, this is an issue with RAM consumption when processing large attachments. In our current implementation they all have to be loaded fully into the RAM. Which likely causes memory overflow errors on large attachements. 

To be sure about that, it would be very helpful, if you could send the error.log file

**Comment by julian3005** [comment]
We have found the issue. We are using the Postfix Mail Transfer Agent and it had a limit of 10 MB.
