### ISSUE TITLE
Solr synchronization improvements

### ISSUE THREAD

**Issue by fedys** [cross-solution/YAWIK#287]
1. The [JobEventSubscriber::updateIndex()](https://github.com/cross-solution/YAWIK/blob/develop/module/Solr/src/Solr/Listener/JobEventSubscriber.php#L93) calls the [Manager::addDocument()](https://github.com/cross-solution/YAWIK/blob/develop/module/Solr/src/Solr/Bridge/Manager.php#L72) which in turn calls the [SolrClient::commit()](https://github.com/cross-solution/YAWIK/blob/develop/module/Solr/src/Solr/Bridge/Manager.php#L77) on every [postPersist](https://github.com/cross-solution/YAWIK/blob/develop/module/Solr/src/Solr/Listener/JobEventSubscriber.php#L65) and [postUpdate](https://github.com/cross-solution/YAWIK/blob/develop/module/Solr/src/Solr/Listener/JobEventSubscriber.php#L75) event. The SolrClient::commit() should be called only once on a postFlush event.
2. The [SolrClient::optimize()](https://github.com/cross-solution/YAWIK/blob/develop/module/Solr/src/Solr/Bridge/Manager.php#L78) should not be called on every SolrClient::commit(). It should be called once a day (via cron) or not called at all (see [Solr WiKi](http://wiki.apache.org/solr/SolrPerformanceFactors#Optimization_Considerations))

**Comment by TiSiE** [comment]
#### 1.
Ideally, the solr index should only be updated, if the status of the job changed
* from a non-active status to active -> commit
* from any status to inactive -> remove

That allows for reviewing changes to an already activated job when using the solr module.

It also means, we need a way to indicate status changes in the job entity, so the listener knows, when to act. Ideas?

#### 2.
We will work on that, when we found that to be a significant performance hit.

**Comment by fedys** [comment]
@TiSiE the status change can be detected via `Doctrine\ODM\MongoDB\Event\PreUpdateEventArgs::getOldValue() ` and `::getNewValue()`

**Comment by TiSiE** [comment]
@fedys Great!

That leads to a listener like:
``` php

class UpdateSolrIndexListener
{
    public function getSubsribedEvents() 
    {
        return [ 'preUpdate', 'postUpdate', 'postFlush' ];
    }

    public function preUpdate(PreUpdateArgs $args)
    { /* check status change here, store it for the document in a class property */ }

    public function postUpdate(LifecycleArgs $args)
    { /* Add document to solr index, when flag is set */ }

    public function postFlush($args)
    { /* commit (and optimize) solr, if SOMETHING was commited. */ }
}
```

We then do not need the addDocument method of the manager anymore.

**Comment by fedys** [comment]
@TiSiE I am with you. Do you want me to refactor it the way you described above?
