### ISSUE TITLE
Caching organization images

### ISSUE THREAD

**Issue by TiSiE** [cross-solution/YAWIK#298]
To address #196, we need a caching mechanism for organization images. Preferably store them directly in the filesystem underneath the web servers document root. 

* We **do not need** to consider permissions, as organization images are always public. 
* The images **should** still be stored in the database.
* On first access on an image, a cached version **should** be created.
* On changes to or deletion of the image, the cached version **should** be removed

----
One possible solution:
* Hook into "no route" event and check if an image was beeing requested.
  * if so, create a cached version.
  * (This cached version must have the image database id in the name)
* When image is deleted or updated throw an event.
  * Hook to this event to delete the cached version.

**Comment by TiSiE** [comment]
@fedys Can you do this?

**Comment by fedys** [comment]
@TiSiE  yes, I can start working on it on Monday.
