### ISSUE TITLE
Strip base URL during detecting organization image URI

### ISSUE THREAD

**Issue by fedys** [cross-solution/YAWIK#305]
An URI should be striped of a base URL [before matching an image ID](https://github.com/cross-solution/YAWIK/blob/9ee500f56fab218291a91b832f48b4c59af6b58e/module/Organizations/src/Organizations/ImageFileCache/ApplicationListener.php#L58)

**Comment by TiSiE** [comment]
My idea was to pass the base path as optional parameter, but stripping is even better. Go ahead.
