### ISSUE TITLE
Upgrade to doctrine/mongodb-odm to 1.1.x

### ISSUE THREAD

**Issue by fedys** [cross-solution/YAWIK#312]
It would be great to upgrade Doctrine ODM to 1.1.x. Unfortunately, there are several BC breaks.

**Comment by TiSiE** [comment]
So ... tell us __what exactly__ are these BC breaks in particular. :smile:

**Comment by fedys** [comment]
1. I noticed problem with `Core\Entity\ModificationDateAwareEntityTrait::setDateCreated(DateTime $dateCreated = null)` ODM 1.1 passes `Doctrine\ODM\MongoDB\Event\LifecycleEventArgs` instance while  ODM 1.0 passes nothing
2. I overlooked ODM 1.1 requires PHP "^5.6 || ^7.0" thus upgrade is not possible  for your evironment now :(

**Comment by fedys** [comment]
There may exist other BC breaks as well. I did not test it thoroughly yet.

**Comment by cbleek** [comment]
I'll recheck, if we can upgrade.

**Comment by cbleek** [comment]
We can upgrade. All productive yawik instances we know are currently running php5.6 or can be upgraded.

When upgrading my local instance from php5.5 to php5.6  I'got the exception

`2016-11-10 10:56:43 EXCEPTION mongo2:27017: exception: Index with name: permissions_view_1 already exists with different options in /home/cbleek/Projects/YAWIK/vendor/doctrine/mongodb/lib/Doctrine/MongoDB/Collection.php on line 312`

I got my YAWIK running again by deleting all mongo indizes, However.

We can point out this issue in the Release notes. 

So let's upgrade.

**Comment by fedys** [comment]
Great news! Do you want me to carry out the upgrade? I will go over the ODM 1.1 changelog and note the possible BC breaks. Then I will try to detect them in YAWIK (some of them are already detected) and fix them.

**Comment by cbleek** [comment]
> Great news! Do you want me to carry out the upgrade?
>
Yes.

How do you rate the time? Can we'll make it in a couple of weeks, or 
will it be finished next year.

**Comment by fedys** [comment]
I assume there are minor BC breaks only. Estimated time is within a week. I will know more details after an initial research.
