### ISSUE TITLE
Comfortable debugging via nette/tracy

### ISSUE THREAD

**Issue by fedys** [cross-solution/YAWIK#314]
I am using [nette/tracy](https://github.com/nette/tracy) for several years and must say it is an awesome tool for visualization and logging (including email error reporting) of Exceptions/Errors.

This could be a great replacement for the current error reporting/logging. I find it a bit uncomfortable.

**Comment by cbleek** [comment]
just do it.

**Comment by TiSiE** [comment]
I'm still not totally convinced, this adds benefits to Firefox/Chrome Dev-Tools and Xdebug/ZendDebugger....

Although I am a little thrilled by the error logging functionality in production mode, which could definitively replace our current somewhat messy solution.....

I guess, I have to see it in action .... so I am waiting for a pull request :)

**Comment by fedys** [comment]
I just made a pull request containing a Tracy usage demonstration. This shows features in development and production mode as well. If Tracy is enabled (currently default) then previous error handling is switched off. 

I do not know if you have currently some mechanism that lets you know about possible errors in production mode via email. Tracy allows this in a easy way. All you have to do is to specify email address and Tracy send you an email in case of an error. There is of course a snoozing feature to avoid bursting your mailbox. Default value is 900 seconds which means do not send more than one email every 15 minutes. In addition, every error (starting from notice level) is logged in /logs/tracy/error.log plus for every unique exception is generated an extra html file with an exception trace.

In development mode, Tracy does no file / email logging. It just display an exception trace screen. This also applies for notices (this can be switched off via 'strict' flag in configuration).

This pull request is meant only for a Tracy feature demonstration. Mails are sent via Tracy's default implementation (means via mail() function). Please let me know your thoughts and possible improvements.

**Comment by cbleek** [comment]
Hi @fedys , it works really cool. Thank you.

We should cleanup and remove our own error handling code. But we can do this later.I leave the issue open.

**Comment by fedys** [comment]
Ok

**Comment by cbleek** [comment]
Cleanup was done, So we close this issue
