### ISSUE TITLE
an upgrade of ircmaxell/random-lib to 1.2.0 leads to an error

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#317]
`2016-11-22 10:30:01 ERR Class Zend\Math\Source\HashTiming contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (RandomLib\Source::isSupported) (errno 1) in /home/cbleek/Projects/YAWIK/vendor/zendframework/zend-math/src/Source/HashTiming.php on line 111`

**Comment by cbleek** [comment]
I've added the ircmaxell/random-lib to our composer.json some tme ago, because there was an error after a composer upgrade. I doubt that we need the package at all.

**Comment by TiSiE** [comment]
RandomLib is needed by Zend_Math for PHP < 7. Zend Math is used in module Auth (UserUniqueTokenGenerator.php) and will therefor remain in Yawik at version 1.1 until PHP 5 support is dropped.
