### ISSUE TITLE
an applicant can receive a confirmation Mail, even if the submit of the applications fails

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#321]
https://groups.google.com/d/msgid/yawik/b72bb6f0-2975-4397-93e6-2f6d7631f732%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by cbleek** [comment]
we have to make sure that the confirmation mail is sent after the CC mail to the applicant

**Comment by TiSiE** [comment]
The main problem here is, that the application is not saved before the listeners for the mail sending are triggered AND that the PersistenceListener is NOT called when the listeners errored (although it SHOULD get called). 

The fix here is to save the application manually BEFORE the listeners are  triggered.
