### ISSUE TITLE
Location can get lost, when editing the job title

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#326]
This might be a bug in the Geo Module

**Comment by cbleek** [comment]
@TiSiE this was done, wasn't it?

**Comment by utrenkner** [comment]
Geo search seems completely broken - therefore, this cannot be tested.

**Comment by utrenkner** [comment]
Thanks. Now the location remains when editing again the same jobs.

However, the location does neither show up in the overview page (jobboard) nor does the geo-search take it into account (whatever location I search for, my new test job shows ups).

**Comment by TiSiE** [comment]
Sorry, that is a problem with the [yawik/Solr](https://github.com/yawik/Solr) module
