### ISSUE TITLE
Search for companies like "Ärzte ohne Grenzen" (with non-ascii characters) fails

### ISSUE THREAD

**Issue by utrenkner** [cross-solution/YAWIK#332]
Seems someone worked on this issue - but still not solved?

https://github.com/cross-solution/YAWIK/commit/bec80eb7ff9e1936ce538021859c510371a0be77

**Comment by cbleek** [comment]
the search für company names with "Umlauts" is working now in our demo. 

Unfortunately the latest commit breaks storing of the location of a job. This will be fixed in #333
