### ISSUE TITLE
Unittest fixes and factories update

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#341]
After makeing the factory zf3 compatibe in https://github.com/cross-solution/YAWIK/commit/975a056245b3759e1a000eb2058ce8233b1c7fae, test fails

Please fix the tests

* https://github.com/cross-solution/YAWIK/blob/develop/module/Core/test/CoreTest/Factory/View/Helper/SocialButtonsFactoryTest.php#L42
* https://github.com/cross-solution/YAWIK/blob/develop/module/Organizations/test/OrganizationsTest/Mail/EmployeeInvitationFactoryTest.php#L166

In addition, please make the following factories ZF3 compatible
* [module/Organizations/src/Organizations/Factory/Controller/Plugin/InvitationHandlerFactory.php](https://github.com/cross-solution/YAWIK/blob/develop/module/Organizations/src/Organizations/Factory/Controller/Plugin/InvitationHandlerFactory.php)
* [module/Core/src/Core/Factory/OptionsAbstractFactory.php](https://github.com/cross-solution/YAWIK/blob/develop/module/Core/src/Core/Factory/OptionsAbstractFactory.php)

**Comment by kilip** [comment]
Hi @cbleek,

I don't have any fail test in my phpunit, so I don't know what to do with that `SocialsButtonFactoryTest` and `EmployeeInvitationFactoryTest`. If you still have that fail test issue please let me know.

**Comment by cbleek** [comment]
@kilip the tests where already fixed by @TiSiE . He had forgotten to mention it:-)
