### ISSUE TITLE
mvctranlator problem

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#351]
**[ZF3 Upgrade](https://github.com/cross-solution/YAWIK/issues/335)** 

----

I've commented https://github.com/cbleek/YAWIK/blob/feature/ZF3/module/Core/Module.php#L73

Otherwise the following Error occurs.

`Catchable fatal error: Argument 1 passed to Zend\Validator\AbstractValidator::setDefaultTranslator() must be an instance of Zend\Validator\Translator\TranslatorInterface, instance of Zend\I18n\Translator\Translator given, called in /home/cbleek/Projects/YAWIK-ZF3/module/Core/Module.php on line 73 and defined in /home/cbleek/Projects/YAWIK-ZF3/vendor/zendframework/zend-validator/src/AbstractValidator.php on line 467`

**Comment by cbleek** [comment]
@TiSiE : the line is still commented. So it propably can be deleted. Isnt it?

**Comment by cbleek** [comment]
@TiSiE please take a look an close the ticket

**Comment by TiSiE** [comment]
@kilip @cbleek 
Now, the error messages of the form validators are **NOT** translated.

example: Apply form:
![yk-351-1](https://user-images.githubusercontent.com/2029304/30606231-45a69d10-9d71-11e7-9e90-bcd28c036d40.png)

**Comment by cbleek** [comment]
by removing the comments, the translations of error messages will work now. We've just tested it.
