### ISSUE TITLE
Login via Facebook is broken

### ISSUE THREAD

**Issue by TiSiE** [cross-solution/YAWIK#363]
HybridAuth throws the Exception "Authentication failed! Facebook returned an invalid user id."

Probably Facebook changed its API and we need to upgrade HybridAuth.

**Comment by cbleek** [comment]
[HAuth](https://github.com/hybridauth/hybridauth/blob/v2/CHANGELOG) Log says ...

> 2.8.0 - October 29 2016
>       BREAKING:
>         #688 - [Facebook] Update Provider to use newer API version

**Comment by cbleek** [comment]
@fedys : can you take a look to this issue? It'seems, that we have to upgrade HybridAuth. Can you try to do this?

**Comment by fedys** [comment]
Yes, I can look at that on this weekend.

**Comment by cbleek** [comment]
Perfect. If you need access to the facebook app used by our demo, please 
let me know.

**Comment by TiSiE** [comment]
Fixed in 2eed95beb1b8663e4475442ce1af6edf4a5f751b 
Merged into [release/0.29](https://github.com/cross-solution/YAWIK/commits/release/0.29)

**Comment by cbleek** [comment]
Facebook login is working.

Bit now linkedin is broken. I've created: https://github.com/cross-solution/YAWIK/issues/366
