### ISSUE TITLE
Social view profile data undesired output

### ISSUE THREAD

**Issue by fedys** [cross-solution/YAWIK#368]
There is a `Doctrine\Common\Collections\ArrayCollection@0000000004e41eea00007f28bf1cf45a` output in a profile data modal window after clicking a _view profile data_ link in _/my/profile_ page. This is caused by `<?=$profile->getEmployments()?>` in [/module/Applications/view/applications/manage/social-profile.phtml](https://github.com/cross-solution/YAWIK/blob/release/0.29/module/Applications/view/applications/manage/social-profile.phtml#L17)

**Comment by cbleek** [comment]
I see. Thank's for reporting
