### ISSUE TITLE
Error 500 after creating an application

### ISSUE THREAD

**Issue by julian3005** [cross-solution/YAWIK#374]
When submitting an application i get an error 500. 

 PHP Fatal error:  Call to a member function getUri() on null in .../yawik/htdocs/module/Applications/src/Applications/Controller/ApplyController.php on line 316

**Comment by cbleek** [comment]
Which version are you using?

The is a getUri() call. But in Line 319 (master/develop)

https://github.com/cross-solution/YAWIK/blob/develop/module/Applications/src/Applications/Controller/ApplyController.php#L319

it seems, there is a problem with rthe fileupload.

**Comment by julian3005** [comment]
We are using v0.29 (master) an i get the error on your demo database too. Also happens without any attached files.

Here is our ApplyController (renamed to .txt to upload it here)
[ApplyController.txt](https://github.com/cross-solution/YAWIK/files/1024607/ApplyController.txt)

Test on yawik.org/demo: 
![erroryawik2](https://cloud.githubusercontent.com/assets/22173482/26389956/b9fad4e6-405c-11e7-8a41-0a2a4ca1a6f3.jpg)

**Comment by julian3005** [comment]
After further investigating and resolving of other problems, we found that it fails in YAWIK/module/Applications/view/applications/apply/index.phtml in Line 29 where he trys to get the organization image. We have temporarily removed that line so that the useres can at least submit the application without an error.

**Comment by cbleek** [comment]
Do you have php-gd installed? Since 0.29 YAWIK uses imagine für resizing 
organization logos. Imagine requires an image manipulation library like 
"php-gd" or "php-imagick".

**Comment by TiSiE** [comment]
Image manipulation is only done when uploading a new organization image. So it is very unlikely that is the issue here.

It's just that:
"Call to a member function getUri() on null" when trying to load the image from the organizationImageCache which should be an object but is not defined.

**Comment by TiSiE** [comment]
fix will be included in 0.29.1
