### ISSUE TITLE
Search error until session is reset

### ISSUE THREAD

**Issue by julian3005** [cross-solution/YAWIK#375]
When searching for jobs on our site [(jobs.frankwalder.com)](https://jobs.frankwalder.com/de/jobboard)  there is the message "Sorry, loading results failed" and if you reload the site (pressing F5) it generates an error until the session is reset (if i delete the PHPSESSID Cookie i can access the site again)
Error File:
[exception--2017-05-23--11-01--959f8f519d.zip](https://github.com/cross-solution/YAWIK/files/1024891/exception--2017-05-23--11-01--959f8f519d.zip)

Error in Webbrowser: 

> Zusätzliche Informationen:
MongoException
Datei:
/var/www/jobs-frankwalder-com_yawik/htdocs/vendor/doctrine/mongodb/lib/Doctrine/MongoDB/Cursor.php:143
Nachricht:
Cannot run command count(): exception: invalid operator: $search
Stapelverlauf:
0 /var/www/jobs-frankwalder-com_yawik/htdocs/vendor/doctrine/mongodb/lib/Doctrine/MongoDB/Cursor.php(143): MongoCursor->count(false)
1 /var/www/jobs-frankwalder-com_yawik/htdocs/vendor/doctrine/mongodb/lib/Doctrine/MongoDB/Cursor.php(726): Doctrine\MongoDB\Cursor->Doctrine\MongoDB\{closure}()
2 /var/www/jobs-frankwalder-com_yawik/htdocs/vendor/doctrine/mongodb/lib/Doctrine/MongoDB/Cursor.php(144): Doctrine\MongoDB\Cursor->retry(Object(Closure), true)
3 /var/www/jobs-frankwalder-com_yawik/htdocs/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Cursor.php(228): Doctrine\MongoDB\Cursor->count(false)
4 /var/www/jobs-frankwalder-com_yawik/htdocs/module/Core/src/Core/Paginator/Adapter/DoctrineMongoLateCursor.php(92): Doctrine\ODM\MongoDB\Cursor->count()
5 /var/www/jobs-frankwalder-com_yawik/htdocs/vendor/zendframework/zend-paginator/src/Paginator.php(875): Core\Paginator\Adapter\DoctrineMongoLateCursor->count()
6 /var/www/jobs-frankwalder-com_yawik/htdocs/vendor/zendframework/zend-paginator/src/Paginator.php(558): Zend\Paginator\Paginator->_calculatePageCount()
7 /var/www/jobs-frankwalder-com_yawik/htdocs/module/Core/src/Core/Controller/Plugin/CreatePaginator.php(115): Zend\Paginator\Paginator->setItemCountPerPage(10)
8 [internal function]: Core\Controller\Plugin\CreatePaginator->__invoke('Jobs/Board', Array, Object(Zend\Stdlib\Parameters))
9 /var/www/jobs-frankwalder-com_yawik/htdocs/module/Core/src/Core/Controller/Plugin/PaginationBuilder.php(230): call_user_func_array(Object(Core\Controller\Plugin\CreatePaginator), Array)
10 /var/www/jobs-frankwalder-com_yawik/htdocs/module/Core/src/Core/Controller/Plugin/PaginationBuilder.php(202): Core\Controller\Plugin\PaginationBuilder->callPlugin('paginator', Array)
11 /var/www/jobs-frankwalder-com_yawik/htdocs/module/Core/src/Core/Controller/Plugin/PaginationBuilder.php(93): Core\Controller\Plugin\PaginationBuilder->getResult()
12 [internal function]: Core\Controller\Plugin\PaginationBuilder->__invoke(Array)
13 /var/www/jobs-frankwalder-com_yawik/htdocs/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(318): call_user_func_array(Object(Core\Controller\Plugin\PaginationBuilder), Array)
14 /var/www/jobs-frankwalder-com_yawik/htdocs/module/Jobs/src/Jobs/Controller/JobboardController.php(97): Zend\Mvc\Controller\AbstractController->__call('pagination', Array)
15 /var/www/jobs-frankwalder-com_yawik/htdocs/module/Jobs/src/Jobs/Controller/JobboardController.php(97): Jobs\Controller\JobboardController->pagination(Array)
16 /var/www/jobs-frankwalder-com_yawik/htdocs/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Jobs\Controller\JobboardController->indexAction()
17 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
18 /var/www/jobs-frankwalder-com_yawik/htdocs/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
19 /var/www/jobs-frankwalder-com_yawik/htdocs/vendor/zendframework/zend-eventmanager/src/EventManager.php(263): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
20 /var/www/jobs-frankwalder-com_yawik/htdocs/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
21 /var/www/jobs-frankwalder-com_yawik/htdocs/vendor/zendframework/zend-mvc/src/DispatchListener.php(118): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
22 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
23 /var/www/jobs-frankwalder-com_yawik/htdocs/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
24 /var/www/jobs-frankwalder-com_yawik/htdocs/vendor/zendframework/zend-eventmanager/src/EventManager.php(263): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
25 /var/www/jobs-frankwalder-com_yawik/htdocs/vendor/zendframework/zend-mvc/src/Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
26 /var/www/jobs-frankwalder-com_yawik/htdocs/public/index.php(49): Zend\Mvc\Application->run()
27 {main}

**Comment by cbleek** [comment]
Can you drop the indexes of your jobs collections? Indexes are 
recreated, if they do not exists.


set1:PRIMARY> db.jobs.dropIndexes();
set1:PRIMARY> db.jobs.snapshots.dropIndexes();

**Comment by julian3005** [comment]
After updating MongoDB from 2.4 to 3.4 it works again.
