### ISSUE TITLE
Status is immutable

### ISSUE THREAD

**Issue by julian3005** [cross-solution/YAWIK#376]
When activating/deactivating a job posting through the normal ui it fails. This error occurs also on your demo database.

![erroryawik4](https://cloud.githubusercontent.com/assets/22173482/26492063/9aa6a202-4212-11e7-87fd-9837f00baa22.jpg)

Additional information:
Core\Exception\ImmutablePropertyException

File:

    /data/www/clients/client1/web1/YAWIK/module/Core/src/Core/Entity/SnapshotTrait.php:80

Message:

    Property "status" of class "Jobs\Entity\JobSnapshot" is immutable.

Stack trace:

    #0 /data/www/clients/client1/web1/YAWIK/module/Jobs/src/Jobs/Entity/JobSnapshot.php(112): Jobs\Entity\JobSnapshot->immutable('status')
    #1 /data/www/clients/client1/web1/YAWIK/module/Jobs/src/Jobs/Controller/ManageController.php(363): Jobs\Entity\JobSnapshot->changeStatus('inactive', 'Status changed ...')
    #2 /data/www/clients/client1/web1/YAWIK/module/Jobs/src/Jobs/Controller/ManageController.php(214): Jobs\Controller\ManageController->changeStatus(Object(Jobs\Entity\JobSnapshot), 'inactive')
    #3 /data/www/clients/client1/web1/YAWIK/module/Jobs/src/Jobs/Controller/ManageController.php(129): Jobs\Controller\ManageController->save()
    #4 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Jobs\Controller\ManageController->editAction()
    #5 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
    #6 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
    #7 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-eventmanager/src/EventManager.php(263): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #8 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
    #9 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-mvc/src/DispatchListener.php(118): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
    #10 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
    #11 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
    #12 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-eventmanager/src/EventManager.php(263): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #13 /data/www/clients/client1/web1/YAWIK/vendor/zendframework/zend-mvc/src/Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
    #14 /data/www/clients/client1/web1/YAWIK/public/index.php(49): Zend\Mvc\Application->run()
    #15 {main}

**Comment by TiSiE** [comment]
fix will be included in 0.29.1
