### ISSUE TITLE
Feature Request: Publishing job according to Google's Job Postings specs

### ISSUE THREAD

**Issue by utrenkner** [cross-solution/YAWIK#387]
[Google is moving into job search](https://blog.google/products/search/connecting-more-americans-jobs/) - and YAWIK should use the new options.

As soon as possible, YAWIK should start publishing jobs according to [Google's Job Postings specs](https://developers.google.com/search/docs/data-types/job-postings). Now available only in the US, Google will certainly roll-out the integration of job search into its general search in other parts of the world.

**Comment by utrenkner** [comment]
Actually, the spec's are not Google's but available here https://schema.org/JobPosting

**Comment by cbleek** [comment]
Good idea. Since Google now proposes to use JsonLD we can create a filter and a view helper. This makes it much easier to structured data to the job as suggested in #181 

Within a job template it should be possible to add the semantic data simply like <?=$this->semanticData()?>
