### ISSUE TITLE
ZF3: Jobs/Form/Multiposting throws Exception, if product is chosen.

### ISSUE THREAD

**Issue by TiSiE** [cross-solution/YAWIK#397]
Unable to resolve service "filtermanager" to a factory;

    #6 /var/www/zf3.yawik.org/module/Jobs/view/form/multiposting-select.phtml(77): 
       Zend\View\Renderer\PhpRenderer->services('filtermanager.J...')

**Comment by cbleek** [comment]
was fixed in https://github.com/cross-solution/YAWIK/commit/f1bdc80d817f5f41cc03541f11bda13526ba503e
