### ISSUE TITLE
ZF3: Jobs/Form/Template: Saving changes returns "Server error"

### ISSUE THREAD

**Issue by TiSiE** [cross-solution/YAWIK#398]
In the tracy error log, the following line appears:

    PHP Notice: Undefined property: Jobs\Controller\TemplateController::$serviceLocator 
                in module/Jobs/src/Jobs/Controller/TemplateController.php:181

**Comment by cbleek** [comment]
@kilip: can you fix this?

**Comment by kilip** [comment]
@cbleek,

Yes, I can fix this.

**Comment by cbleek** [comment]
Very good. So please fix it.

**Comment by TiSiE** [comment]
Unfortunately, this seems to NOT be fixed.
![yk-398-screen1](https://user-images.githubusercontent.com/2029304/30441261-2ff60560-9979-11e7-8cb8-e815bd4fcffa.png)

**Comment by kilip** [comment]
@TiSiE I can't produce that Fatal Error in my local yawik. But I have found this error:

> Undefined method: 'persist'. The method name must start with 'findBy' or 'findOneBy'!

And that error fix in 24efbb6
