### ISSUE TITLE
ZF3: upload of a profile photo does not work.

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#399]
![auswahl_999 509](https://user-images.githubusercontent.com/858642/29962017-d56f8642-8f01-11e7-9885-7e2fc2558f99.png)

@kilip can you take a look?

**Comment by kilip** [comment]
I am working on this issue now.

**Comment by kilip** [comment]
@cbleek I can't reproduce error for this issue. Looks like it's already fixed in my #411 pull requests

**Comment by cbleek** [comment]
Yes, this works now. Thank you!
