### ISSUE TITLE
Creating new job fails in Demo - form and preview end in HTTP 500

### ISSUE THREAD

**Issue by utrenkner** [cross-solution/YAWIK#401]
The second step - entering the job ad details - fails with HTTP 500. So does the preview.

**Comment by cbleek** [comment]
It happens with the "Default" template only.  So I think it has something to do with the Google Jobs JSON, which is included in Default template only.

https://github.com/cross-solution/YAWIK/blob/develop/module/Jobs/public/templates/default/index.phtml#L4

Error Message:

`[2017-09-11 09-01-24] Fatal Error: Call to a member function format() on null in /var/www/yawik.org/module/Jobs/src/Jobs/Entity/Decorator/JsonLdProvider.php:56  @  https://yawik.org/demo/en/jobs/editTemplate/59b62f120acec31d6bb03b88  @@  exception--2017-07-08--11-05--e59b3e32e0.html
`

**Comment by TiSiE** [comment]
The JsonLdProvider did assume, there is a publish date set - which might not be the case on a new job draft.
