### ISSUE TITLE
Making address fields consistent

### ISSUE THREAD

**Issue by utrenkner** [cross-solution/YAWIK#406]
When entering the main company/organisation, one has to separately enter a street number but no country. But country should be a mandatory field, here.

When entering an invoice address, there is no separate field for street number but a country.

**Comment by cbleek** [comment]
address fields are consistent now. 

Formulars will be configurable. Currently the Invoice Firm can be configured by https://github.com/yawik/Orders/blob/develop/config/InvoiceAddressOptions.config.local.php.dist

example
```

'region' => [
		'enabled' => true,
                'required' =>true,
                'options' => [
        'value_options' => [
            'key1' => 'Stuttgart',
            'key2' => 'München',
            'key3' => 'Frankfurt',
        ]
    ],
    'attributes' => [
        'class' => '',
        'data-searchbox' => '-1',
        'data-placeholder' => /*@translate*/ 'please select',
        'data-allowclear' => 'true',
    ],
    'type' => 'select',
],
```

would create a selection box with the values "Stuttgart", "München", "Frankfurt"
