### ISSUE TITLE
Admin cannot change into a recently created User

### ISSUE THREAD

**Issue by utrenkner** [cross-solution/YAWIK#408]
This has probably to do with caching or not-updating of a view: For (quite) some time after a new user was created, the Admin does not see her/him in the list of users he can change into. If the list is not updated immediately, then the interval for this update must be very small.

Use case: A company creates a new user, does something and then calls the Admin for help. Then he must be able to become that user in order to change/complete what s/he was doing.

**Comment by cbleek** [comment]
fixed in https://github.com/cross-solution/YAWIK/pull/586/commits/599b15e22958f06bb697853254e4ce5b751d4b3a
