### ISSUE TITLE
Changing user back to the Admin is difficult/unclear

### ISSUE THREAD

**Issue by utrenkner** [cross-solution/YAWIK#409]
As Admin, when editing an existing job of a different user, the Admin automatically switches to become that user. When done, it can be difficult to become the Admin again. One has to go on a page which is not tied to the other user and then switch back (i.e. switching back does not work when one is still in the other user's job ad, in the other user's overview of his jobs, in the other user's overview of companies etc.). This is cumbersome.

Ideally, it should work like this: When the Admin clicks to re-become himself, a pop-up asks "Do you really want to switch user" (or similar). When ok'ed, he should see either the last page viewed before becoming a different user (usually the job board), or else the default page that is shown after the Admin logged in.

**Comment by TiSiE** [comment]
User switching is improved in 665bb40.

When clicking "Clear switched user" one is taken back exactly where one started from. The complete session is restored as well. (Inclusive filter form parameters)
