### ISSUE TITLE
[ZF3] when deleting an organization logo, reference from the organization entity is not deleted.

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#412]
If  the organization logo is deleted, you'll get an error like 

```
Doctrine\ODM\MongoDB\DocumentNotFoundException
File:
/var/www/zf3.yawik.org/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/DocumentNotFoundException.php:32
Message:
The "DoctrineMongoODMModule\Proxy\__CG__\Organizations\Entity\OrganizationImage" document with identifier "59bab4980acec31623d66c9e" could not be found.
```
it only happens on the ZF3 branch

![auswahl_999 525](https://user-images.githubusercontent.com/858642/30480223-ff3c1fe0-9a18-11e7-9718-544fbb010ad5.png)

**Comment by cbleek** [comment]
@kilip can you take a look at this?

**Comment by kilip** [comment]
@cbleek  I am working on this issue now

**Comment by kilip** [comment]
Sorry @cbleek looks like I can't fix this issue, I don't have a good understanding with doctrine mongodb relation. Looks like this problem caused by doctrine reference issue. ```Organizations\Entity\OrganizationImage``` entity always have null value on ```$organization``` property, that's why the `OrganizationImage::preRemove` code never executed:

```    
    /**
     * Tells Doctrine to delete the image reference, if the image is deleted.
     *
     * @ODM\PreRemove()
     */
    public function preRemove()
    {
        if ($org = $this->getOrganization()) {
            $this->getOrganization()->setImage(null);
        }
    }
```

**Comment by cbleek** [comment]
OK. @TiSiE can you help?

**Comment by cbleek** [comment]
Shouldn't the listener be mentioned in our documentation?
http://yawik.readthedocs.io/en/latest/modules/core/index.html#events

**Comment by TiSiE** [comment]
@cbleek @kilip 
Yes, I can!

Organizations do not use a single image anymore, but [ImageSets](https://github.com/cross-solution/YAWIK/blob/478992919eb6796eecb977eb8db866b9101dac4a/module/Core/src/Core/Entity/ImageSet.php) instead. (That was implemented to be able to store images in different sizes like thumbnail and original).

The code quoted above is for backwards compatibility and is not used anymore for new organization entities.

The removing of references for ImageSets is done by [DeleteImageSetListener](https://github.com/cross-solution/YAWIK/blob/478992919eb6796eecb977eb8db866b9101dac4a/module/Core/src/Core/Listener/DeleteImageSetListener.php), which is registered in the event manager with the key 'Core/File/Events'.
([Core/module.config.php#502](https://github.com/cross-solution/YAWIK/blob/478992919eb6796eecb977eb8db866b9101dac4a/module/Core/config/module.config.php#L502)).

However, that listener was removed in 2a516cb350ed8b0561324cfcdb23add04ac0a127, effectively caused this issue.

@kilip is to blame here for removing the lines :stuck_out_tongue_winking_eye: , as well as myself for approving the changes :angry: . We (and by we, I mean mostly me) need to improve on pull request reviews.. :confused: 

Anyway, it's working again :smile:

**Comment by TiSiE** [comment]
@cbleek probably....

**Comment by kilip** [comment]
@cbleek , @TiSiE 

Looks like this issue still not fixed. If possible please reopen the issue and assign me to fix this issue

**Comment by TiSiE** [comment]
It WAS fixed.

However, it's broken again. 

Because of the [LazyControllerFactory](https://github.com/cross-solution/YAWIK/blob/09456b0295abc800060f4e837649b405f4b3f903/module/Core/src/Core/Factory/Controller/LazyControllerFactory.php). When creating the FileController, the __wrong__ EventManager gets injected! Must be the 'Core/File/Events', but instead is the 'Core/Ajax/Events'. 

So, I say using LazyControllerFactory MAY NOT be a good idea, especially in this case! We should always create dedicated factories. (which is the recommend way in ZF anyway.)

---

Still, there will be a new issue for that!

**Comment by kilip** [comment]
@tisie

To prevent this happening again I will create a behat feature to test this add and remove logo functionality
