### ISSUE TITLE
Cleanup Error Handling

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#416]
@fedys 

I would like you to cleanup our error handling code. In #314 I've said, that we can do it later. We should do it now.

We're currently move all the code to ZF3. So you should do the Cleanup in the https://github.com/cross-solution/YAWIK/tree/feature/ZF3 Branch

@TiSiE can you shortly describe the task technically, please

**Comment by TiSiE** [comment]
It's pretty simple, actually. As said in #314, we do not want duplicate error handling, so we remove our error handling code and let tracy do its magic. Making it a mandatory requirement for YAWIK, not optional as it is now.

Which means, tracy should also display the error message screen in production mode, as well as log and email the error or fatal error. Of course, no error detail should be shown in production environments...

**Comment by fedys** [comment]
@TiSiE Thanks for the clear instructions. I will take a look at it at the end of this week.

**Comment by fedys** [comment]
I am working on it.

**Comment by cbleek** [comment]
The Cleanup was done in https://github.com/cross-solution/YAWIK/commit/fa8041c1c98b60136f191cf8b58097daddce312b

So we can close this issue. Right?

**Comment by fedys** [comment]
Yes.

**Comment by cbleek** [comment]
OK. 
But our documention is not correct any more
http://yawik.readthedocs.io/en/latest/modules/core/logging.html
http://yawik.readthedocs.io/en/latest/configuration.html#debugging

Can you update it, please?

**Comment by fedys** [comment]
Yes, I can. I will let you know when I finish it.

**Comment by fedys** [comment]
Done via the PR https://github.com/cross-solution/YawikDocs/pull/2

**Comment by cbleek** [comment]
Thank you

**Comment by fedys** [comment]
You are welcome
