### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by sithuhlaing** [cross-solution/YAWIK#421]
I just found that fileupload for pdf, but there are validation which is come from type which is application/pdf but actual is applications/pdf. I don't know how to change the code.

**Comment by cbleek** [comment]
just notice, that my answer per mail didn't reach this issue...


----------------


Fileupload is configured in:

https://github.com/cross-solution/YAWIK/blob/develop/module/Applications/config/applications.forms.global.php.dist

Copy this file into the config/autoload directory and name it applications.forms.global.php


Regards,

Carsten

**Comment by cbleek** [comment]
Ah, you mean the default value is incorrect. Default value is defined in

https://github.com/cross-solution/YAWIK/blob/develop/module/Applications/src/Applications/Options/ModuleOptions.php#L38

Yes, I think application/pdf  is the right value. Feel free to send a puu request.
