### ISSUE TITLE
Page request is so slow

### ISSUE THREAD

**Issue by sithuhlaing** [cross-solution/YAWIK#423]
I found out page request is too slow by using with docker. How can I optimize YAWIK. Thanks a lot.

**Comment by cbleek** [comment]
On each request we currently call an "ensureIndex". This line creates indexes, if they are not existing.

Try to comment the line an test, if the requests gets faster.

https://github.com/cross-solution/YAWIK/blob/develop/module/Core/src/Core/Repository/DoctrineMongoODM/DocumentManagerFactory.php#L35

**Comment by cbleek** [comment]
ensureIndex was removed. It's not needed any more. Will be available in 0.32
