### ISSUE TITLE
Use composer's autoloader

### ISSUE THREAD

**Issue by TiSiE** [cross-solution/YAWIK#428]
As outlined in #419, we want to use composer's autoloader also for loading (default) module's files/classes.

This means:
* adding namespace configuration to composer.json's "autoloader" and "autoloader-dev" sections.
* removing ZF autoloader configuration from all Module.php files.
* adding "optimize-autoloader" and "apcu-autoloader" keys to composer.json's "config" section.

**Comment by cbleek** [comment]
I've just added an initial test and integrated travis/coveralls to the [SimpleImport Module](https://github.com/yawik/SimpleImport.git)

The module currently only works, if the SimpleImport Namespace is added to the [composer.json](https://github.com/cross-solution/YAWIK/blob/develop/composer.json) of the yawik installation. In addition an `composer dump` (as @fedys  has mentioned) has to be executed.

```
    "autoload": {
        "psr-4": {
            "SimpleImport\\": "module/SimpleImport/src"
        }
    }
```

Currently a "travis" version of the composer.json is copied and the `composer dump` is executed via travis.yml. 

https://travis-ci.org/#L1151

We have to keep this in mind, when doing this task.  We should do this in 0.31. @TiSiE ?

**Comment by TiSiE** [comment]
I stumbled upon some interesting projects from zendframework and zfcampus, which might help us solve our Module installing/activating issues:

enable/disable autloading for a module:
https://github.com/zfcampus/zf-composer-autoloading

Activate module on installation:
https://github.com/zendframework/zend-component-installer

As far, as I can tell, this requires some manual steps to be taken:
* Install module
* enable autoloading

----

Another composer-plugin comes from wikimedia:
https://github.com/wikimedia/composer-merge-plugin

@fedys, @cbleek What do you think?

**Comment by kilip** [comment]
I am 100% agree with @TiSiE

I think it will be great too if we can split our modules from `cross-solution/YAWIK` repo into `yawik/*` repo too.  We can do this by using git subplit command. So in `yawik` organization repo we will have repository like:

`yawik/Core`
`yawik/Application`
`yawik/Auth`
....

We can include this required yawik module during developing additional module like SimpleImport, and also easily upgrade yawik installation.

**Comment by fedys** [comment]
Autoload definitions for required modules (Core, Auth, ...) can be permanently written in the composer.json. Autoload definitions for optional modules (SimpleImport, Solr, ...) can be added to the composer.json via the zf-composer-autoloading project. But there are still two issues:
1. Using the zf-composer-autoloading project will modify the composer.json (a developer must avoid commit such change)
2. An optional module with another dependencies (e.g. SimpleImport depends on willdurand/geocoder) needs to be installed via "composer require" command anyway.
