### ISSUE TITLE
fix Behat Tests

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#431]
Hi @kilip ,

Behat tests are currently failing. Can you take a look please.

**Comment by TiSiE** [comment]
@kilip Also please drop some explanation, what the logs are supposed to contain.
In the latest build there are three logs from /build/behat/*.log that just contain the html of the start page, but no information about which scenario they belong to or what was expected....

Same for the screenshots...

**Comment by cbleek** [comment]
@kilip do you know when you can do this task?

**Comment by kilip** [comment]
@TiSiE failed scenario already reported in the end of behat tests:
https://travis-ci.org/cross-solution/YAWIK/builds/285696741#L1447

**Comment by cbleek** [comment]
Thank you!
