### ISSUE TITLE
Snapshots needs Statuses

### ISSUE THREAD

**Issue by TiSiE** [cross-solution/YAWIK#437]
We've implemented the ability to create snapshots of entities via:

* [Core/SnapshotInterface](https://github.com/cross-solution/YAWIK/blob/41acfa8ffd737748034e3d1cece5e0197674aeff/module/Core/src/Core/Entity/SnapshotInterface.php)
* [Core/SnapshotTrait](https://github.com/cross-solution/YAWIK/blob/41acfa8ffd737748034e3d1cece5e0197674aeff/module/Core/src/Core/Entity/SnapshotTrait.php)

and currenttly used in the Jobs module:

* [Jobs/JobSnapshot](https://github.com/cross-solution/YAWIK/blob/41acfa8ffd737748034e3d1cece5e0197674aeff/module/Jobs/src/Jobs/Entity/JobSnapshot.php)

Snapshots (specifically the [SnapshotMeta](https://github.com/cross-solution/YAWIK/blob/41acfa8ffd737748034e3d1cece5e0197674aeff/module/Jobs/src/Jobs/Entity/JobSnapshot.php) embedded document) is draftable to distinguish between active (unmerged) and merged snapshots. 

As it is showing now, in the context of the jobs module, this is not enough. We need specific statuses of the snapshots to determine wether they were accepted, rejected, active. 

So Snapshots needs to be State-Aware, which can be easily added with [Core/StatusAwareInterface](https://github.com/cross-solution/YAWIK/blob/41acfa8ffd737748034e3d1cece5e0197674aeff/module/Core/src/Core/Entity/StatusAwareEntityInterface.php), [Core/StatusAwareEntityTrait](https://github.com/cross-solution/YAWIK/blob/41acfa8ffd737748034e3d1cece5e0197674aeff/module/Core/src/Core/Entity/StatusAwareEntityTrait.php) and the companion, [Core/StatusInterface](https://github.com/cross-solution/YAWIK/blob/41acfa8ffd737748034e3d1cece5e0197674aeff/module/Core/src/Core/Entity/StatusInterface.php), respective [Core/AbstractStatusEntity](https://github.com/cross-solution/YAWIK/blob/41acfa8ffd737748034e3d1cece5e0197674aeff/module/Core/src/Core/Entity/AbstractStatusEntity.php)

What needs to be done:

1. Make snapshots (at least the JobSnapshot entity) status-aware.
    This can be done by adding the status directly to the snapshot entity (overriding the status from the original entity - which must not be altered by the snapshot anyway) or in the SnapshotMeta document.
    (This needs to be discussed further)
2. Make JobSnapshot Status entity with approppriate states
   * ACTIVE (UNMERGED)
   * ACCEPTED (MERGED)
   * REJECTED 
3. Set the respective status upon actions taken on the snapshot either by the recruiter or by the admin
4. Show the current status in the recruiter's job list (and in the admin's  job list)

------

Related classes to look at:
* [Jobs/ManageController](https://github.com/cross-solution/YAWIK/blob/41acfa8ffd737748034e3d1cece5e0197674aeff/module/Jobs/src/Jobs/Controller/ManageController.php)
* [Jobs/InitialzeJob plugin](https://github.com/cross-solution/YAWIK/blob/41acfa8ffd737748034e3d1cece5e0197674aeff/module/Jobs/src/Jobs/Controller/Plugin/InitializeJob.php)
* [Core/SnapshotRepository](https://github.com/cross-solution/YAWIK/blob/41acfa8ffd737748034e3d1cece5e0197674aeff/module/Core/src/Core/Repository/SnapshotRepository.php)
* [Jobs/view/index/index.ajax](https://github.com/cross-solution/YAWIK/blob/41acfa8ffd737748034e3d1cece5e0197674aeff/module/Jobs/view/jobs/index/index.ajax.phtml)
* [Jobs/view/admin/index.ajax](https://github.com/cross-solution/YAWIK/blob/41acfa8ffd737748034e3d1cece5e0197674aeff/module/Jobs/view/jobs/index/index.ajax.phtml)

**Comment by TiSiE** [comment]
@kilip @fedys Whoever yells first may do this :wink:

**Comment by cbleek** [comment]
Hi @kilip 

do you have time to do this task?

I'll need @fedis to do some final task concerning the SimpleImport module.

**Comment by cbleek** [comment]
Hi @kilip 

is the task description from TiSiE  ok?

regards, carsten

**Comment by kilip** [comment]
Hi @cbleek , @TiSiE 
I start working on this issue now.

**Comment by TiSiE** [comment]
@kilip Did you do anything yet? It would be nice to send a pull request, if so.... If not, you do not need to do anymore.
