### ISSUE TITLE
[Install] Database name must not contain "."

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#447]
dots have do be disallowed in database names

**Comment by cbleek** [comment]
there is a unittest, which checks the filter

https://github.com/cross-solution/YAWIK/blob/develop/module/Install/test/InstallTest/Filter/DbNameExtractorTest.php

**Comment by kilip** [comment]
This issue actually is already fixed in (line 49):
https://github.com/cross-solution/YAWIK/blob/develop/module/Install/test/InstallTest/Validator/MongoDbConnectionStringTest.php#L49

**Comment by cbleek** [comment]
Thank you

@TiSiE next time please let us know about your work:-)
