### ISSUE TITLE
Do not detect language, if LanguageDetection ist disabled

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#449]
We're detecting the language in:

https://github.com/cross-solution/YAWIK/blob/c47b2b2d6197aa08759d484b81d51448349abc71/module/Core/src/Core/Listener/LanguageRouteListener.php#L131

But our LanguageDetect Setting is not used.

https://github.com/cross-solution/YAWIK/blob/c47b2b2d6197aa08759d484b81d51448349abc71/module/Core/src/Core/Options/ModuleOptions.php#L79

**Comment by kilip** [comment]
Any one working on this issue now? Feel free to assign me this task.
