### ISSUE TITLE
Organization Profile page

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#458]
we want to create an organization profile page. It should display Informations about the organization.

* Logo
* Name
* Description

In addition, active jobs should be listed.

It should be possible to 

* enable allway
* enable if ative jobs are a available
* disable

a profile for an organization.

**Comment by kilip** [comment]
@cbleek can you describe more about:

- enable all way
- enable if active jobs are a available
- disable

**Comment by cbleek** [comment]
"enabling allways" meens, a profile can be opened allways. It can be opened, if an organization has not active jobs available.

"enabling, if active jobs are available" means, that a profile should be hidden automatically, if no jobs are available. Such a feature will propably be needed, when generating a list of profiles.

"disable" means, deactivate the profile. Even if there are active jobs.

An additional field to the [form for editing an organisation](https://github.com/cross-solution/YAWIK/blob/develop/module/Organizations/src/Organizations/Form/Organizations.php) which makes it possible to set the value has zo be added.

The JobModule contains an AtsMode Entity, which defines, how applications should be processed. Maybe we should name the field, which defines, how profiles are handled "ProfileMode"

@TiSiE : please take a look at my answer

**Comment by kilip** [comment]
@cbleek @TiSiE 

I don't know how to create a query for filtering organization that have an active jobs, so I leave a `@todo` comment in this [line](https://github.com/kilip/YAWIK/blob/b1fb56ba9eeda091b8b99d36de2cf739f579e234/module/Organizations/src/Organizations/Repository/Filter/PaginationQuery.php#L94)

List organizations profile accessible in: `lang/organizations/profile`
Profile for an organization accessible in: `lang/organizations/profile/:id`
