### ISSUE TITLE
Separate Dashboard

### ISSUE THREAD

**Issue by TiSiE** [cross-solution/YAWIK#460]
Currently, the Dashboard replaces the home/start page, when an user is logged in.

This should be separated, so the home/start page is available to logged in users, too. In addition, a navigation menu entry for the dashboard must be available.

---

Achieving this is simple:

* Modify  [\Core\Controller\IndexController](https://github.com/cross-solution/YAWIK/blob/3062c0760bb6fea15c7f59b6c6e657cec0108347/module/Core/src/Core/Controller/IndexController.php): Move code dedicated to the dashboard functionality to the dashboardAction() method.
* Create a route to the dashboard action [model.config.php:81](https://github.com/cross-solution/YAWIK/blob/3062c0760bb6fea15c7f59b6c6e657cec0108347/module/Core/config/module.config.php#L81) 
* Create an entry in the navigation menu config [module.config.php:250](https://github.com/cross-solution/YAWIK/blob/3062c0760bb6fea15c7f59b6c6e657cec0108347/module/Core/config/module.config.php#L250).
* Add acl rules to enable/disable access to the dashboard route [module.config.php:156](https://github.com/cross-solution/YAWIK/blob/3062c0760bb6fea15c7f59b6c6e657cec0108347/module/Core/config/module.config.php#L156)
* Fix unit and behat tests.

**Comment by cbleek** [comment]
Changes are available in the Demo. So we close this issue.
