### ISSUE TITLE
Error 500 on settings due to old mongodb feature used

### ISSUE THREAD

**Issue by vcorreze** [cross-solution/YAWIK#472]
I installed yawik as test on an ubuntu **bionic beaver** machine (*18.04 LTS*).

Install and config went fine, but everytime I tried to go to the 'settings' view, I obtained an error 500.

After some research, i found in `log/tracy/exception.log` the following line :
`MongoWriteConcernException: localhost:27017: Unknown modifier: $pushAll #9 in (...)yawik/vendor/doctrine/mongodb/lib/Doctrine/MongoDB/collection.php:1442 @ http://localhost:4567/fr/settings`

The following [issue](https://github.com/Automattic/mongoose/issues/5574) explains that $pushAll was deprecated in MongoDB 3.6 wich is installed by default in bionic.

**Comment by mbo-s** [comment]
see #471

**Comment by vcorreze** [comment]
Ok, so I close this duplicate.
