### ISSUE TITLE
merge file_upload_optimization into develop

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#473]
modifications where done my @TiSiE 

it's not already merged, because tests are missing. Please create tests and merge:

https://github.com/cross-solution/YAWIK/tree/file_upload_optimization

into develop..

**Comment by kilip** [comment]
I don't know what test is missing, but I have fixed failed Behat and PHPUnit tests.

Please let me know if I need to create a new tests for this issue.

**Comment by cbleek** [comment]
the file_upload_optimization branch adds a couple of classes.

eg.

https://github.com/cross-solution/YAWIK/blob/file_upload_optimization/module/Core/src/Core/Filter/File/Resize.php

@TiSiE can you add more infos?

**Comment by TiSiE** [comment]
These files are created/modified:
<pre>
module/Core/config/module.config.php
module/Core/src/Core/Acl/FileAccessAssertion.php
module/Core/src/Core/Filter/File/Entity.php
module/Core/src/Core/Filter/File/EntityFactory.php
module/Core/src/Core/Filter/File/Resize.php
module/Core/src/Core/Filter/File/ResizeFactory.php
module/Core/src/Core/Form/View/Helper/FormEditor.php
module/Core/src/Core/Repository/RepositoryService.php
module/Core/src/Core/Repository/SnapshotRepository.php
module/Jobs/src/Jobs/Controller/ManageController.php
module/Jobs/src/Jobs/Filter/ViewModelTemplateFilterAbstract.php
module/Jobs/view/form/preview.phtml
module/Jobs/view/jobs/manage/form.phtml
module/Organizations/config/module.config.php
module/Organizations/src/Organizations/Controller/ProfileController.php
module/Organizations/view/organizations/profile/disabled.phtml
</pre>

Tests should be especially checked/modified/created for these files:

* module/Core/src/Core/Acl/FileAccessAssertion.php (only if present)
* module/Core/src/Core/Filter/File/Entity.php (new test needed)
* module/Core/src/Core/Filter/File/EntityFactory.php (new test needed)
* module/Core/src/Core/Filter/File/Resize.php (new test needed)
* module/Core/src/Core/Filter/File/ResizeFactory.php (new test needed)
* module/Core/src/Core/Form/View/Helper/FormEditor.php (only if present)
* module/Core/src/Core/Repository/RepositoryService.php (only if present)
* module/Jobs/src/Jobs/Filter/ViewModelTemplateFilterAbstract.php (only if present)

**Comment by cbleek** [comment]
Hi @TiSiE 

I've created a merge request.

tests are existing for.

- https://coveralls.io/builds/18884260/source?filename=module%2FCore%2Fsrc%2FCore%2FAcl%2FFileAccessAssertion.php
- https://coveralls.io/builds/18884260/source?filename=module%2FCore%2Fsrc%2FCore%2FFilter%2FFile%2FEntity.php
- https://coveralls.io/builds/18884260/source?filename=module%2FCore%2Fsrc%2FCore%2FFilter%2FFile%2FResize.php
- https://coveralls.io/builds/18884260/source?filename=module%2FCore%2Fsrc%2FCore%2FRepository%2FRepositoryService.php

Tests are missing for an older class. It's a huge class which propably should be refactored. 

- https://coveralls.io/builds/18884260/source?filename=module%2FJobs%2Fsrc%2FJobs%2FFilter%2FViewModelTemplateFilterAbstract.php

@TiSiE what do you think?

**Comment by TiSiE** [comment]
It's alright.There were no test present, and - as you already guessed correctly - the class will be refactored.
