### ISSUE TITLE
create Release v0.31

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#474]
@TiSiE please add some infos, how to do.

checked the commit log and fould the following noteable new features/upgrades.

- company profiles.
- separated startpage/dashboard
- set subject of a mail within mail template

Upgrades

- jquery3
- mongo odm. This release will work with >mongo3.6, which fixes #471

**Comment by TiSiE** [comment]
@kilip  How to release (pretty straight forward):

* Create a release branch named "release-[version]" based on 'develop' and push it to github
* Create a merge request from the release branch to master (this way, we can link to the merge request page from the release message to get a list of all changes)
* Merge the release branch into master (release branch can be removed afterwards.)
* Tag master with an signed annotated tag 'v[version]' (eg. v0.31)
* Merge master into 'develop' (to get the tag in the commit line for 'develop')
* Of course, push all to github.

Release message will then be written by me or @cbleek

**Comment by cbleek** [comment]
Hi @TiSiE 

I've created a Tag on develop.

https://github.com/cross-solution/YAWIK/releases/edit/v0.31

Was this correct?

**Comment by cbleek** [comment]
This time I've created a release using the guthub gui only

https://github.com/cross-solution/YAWIK/releases/tag/v0.31
