### ISSUE TITLE
JobsByOrganizationAPI should return JSON by default, JSON-P via Parameter

### ISSUE THREAD

**Issue by mbo-s** [cross-solution/YAWIK#477]
Currently the jobapi returns JSON-P with a hardcoded yawikParseJobs
https://github.com/cross-solution/YAWIK/blob/develop/module/Jobs/src/Jobs/Controller/ApiJobListByOrganizationController.php#L45
e.g.
https://yawik.org/demo/de/api/jobs/organization/55ae775c6b10f8f05b8b457f

Is it possible to return by default only JSON and JSON-P via a dynamic callback Parameter e.g.
https://yawik.org/demo/de/api/jobs/organization/55ae775c6b10f8f05b8b457f?callback=mycallbackfunction

@TiSiE what do you think?

**Comment by cbleek** [comment]
this is much better than the current hardcoded callback name.  

I've implemented the callback name as an additional 
route parameter.

So an URL will look like api/jobs/organization/55ae775c6b10f8f05b8b457f/myCallBack

**Comment by cbleek** [comment]
Works now as requested

- https://yawik.org/demo/de/api/jobs/organization/55ae775c6b10f8f05b8b457f?callback=test
- https://yawik.org/demo/de/api/jobs/organization/55ae775c6b10f8f05b8b457f
