### ISSUE TITLE
Use JobURLHelper in API

### ISSUE THREAD

**Issue by mbo-s** [cross-solution/YAWIK#478]
The JobAPI does not use the JobUrl-Helper

https://github.com/cross-solution/YAWIK/blob/develop/module/Jobs/src/Jobs/View/Helper/JobUrl.php

https://github.com/cross-solution/YAWIK/blob/develop/module/Jobs/src/Jobs/Model/ApiJobDehydrator.php#L39-L45

The links to external Jobs point always to the internal view https://yawik.org/demo/de/jobs/view?id=XXX and not to the external site.

**Comment by cbleek** [comment]
jobUrl helper is used now
