### ISSUE TITLE
Job Location Edit is broken on yawik.org

### ISSUE THREAD

**Issue by mbo-s** [cross-solution/YAWIK#482]
Location editing on an offer is broken

Steps to reproduce

1. Edit an offer e.g. https://yawik.org/demo/en/jobs/edit?id=592d1de14e197fa34a846ac3 you see here as Location "Berlin, Berlin"
2. Edit "Title and job location"
3. "Berlin, Berlin" will be "Test"
4. Save does not work

> An error occurred during execution; please try again later.
Additional information:
Doctrine\Common\Persistence\Mapping\MappingException
File:
/var/www/yawik.org/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/MappingException.php:37
Message:
The class 'Doctrine\ODM\MongoDB\UnitOfWork' was not found in the chain configured namespaces Core\Entity, Auth\Entity, Cv\Entity, Applications\Entity, Jobs\Entity, Settings\Entity, Geo\Entity, Organizations\Entity, JobsByMail\Entity, Orders\Entity
Stack trace:
#0 /var/www/yawik.org/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/MappingDriverChain.php(112): Doctrine\Common\Persistence\Mapping\MappingException::classNotFoundInNamespaces('Doctrine\\ODM\\Mo...', Array)
#1 /var/www/yawik.org/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataFactory.php(160): Doctrine\Common\Persistence\Mapping\Driver\MappingDriverChain->loadMetadataForClass('Doctrine\\ODM\\Mo...', Object(Doctrine\ODM\MongoDB\Mapping\ClassMetadata))
#2 /var/www/yawik.org/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(332): Doctrine\ODM\MongoDB\Mapping\ClassMetadataFactory->doLoadMetadata(Object(Doctrine\ODM\MongoDB\Mapping\ClassMetadata), NULL, false, Array)
#3 /var/www/yawik.org/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(216): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata('Doctrine\\ODM\\Mo...')
#4 /var/www/yawik.org/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/DocumentManager.php(287): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor('Doctrine\\ODM\\Mo...')
#5 /var/www/yawik.org/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php(1699): Doctrine\ODM\MongoDB\DocumentManager->getClassMetadata('Doctrine\\ODM\\Mo...')
#6 /var/www/yawik.org/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php(2206): Doctrine\ODM\MongoDB\UnitOfWork->doPersist(NULL, Array)
#7 /var/www/yawik.org/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php(1728): Doctrine\ODM\MongoDB\UnitOfWork->cascadePersist(Object(Jobs\Entity\JobSnapshot), Array)
#8 /var/www/yawik.org/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php(1674): Doctrine\ODM\MongoDB\UnitOfWork->doPersist(Object(Jobs\Entity\JobSnapshot), Array)
#9 /var/www/yawik.org/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/DocumentManager.php(412): Doctrine\ODM\MongoDB\UnitOfWork->persist(Object(Jobs\Entity\JobSnapshot))
#10 /var/www/yawik.org/module/Core/src/Core/Repository/RepositoryService.php(52): Doctrine\ODM\MongoDB\DocumentManager->persist(Object(Jobs\Entity\JobSnapshot))
#11 /var/www/yawik.org/module/Jobs/src/Jobs/Controller/ManageController.php(315): Core\Repository\RepositoryService->store(Object(Jobs\Entity\JobSnapshot))
#12 /var/www/yawik.org/module/Jobs/src/Jobs/Controller/ManageController.php(184): Jobs\Controller\ManageController->save()
#13 /var/www/yawik.org/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Jobs\Controller\ManageController->editAction()
#14 /var/www/yawik.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#15 /var/www/yawik.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#16 /var/www/yawik.org/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(106): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#17 /var/www/yawik.org/vendor/zendframework/zend-mvc/src/DispatchListener.php(138): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#18 /var/www/yawik.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#19 /var/www/yawik.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#20 /var/www/yawik.org/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#21 /var/www/yawik.org/public/index.php(56): Zend\Mvc\Application->run()
#22 {main}

**Comment by cbleek** [comment]
Location ist stored correctly to the mongi DB.

The value "Test" comes from, I guess

https://github.com/cross-solution/YAWIK/blob/develop/module/Geo/public/js/geoselect.js#L98
