### ISSUE TITLE
improve travis build for modules

### ISSUE THREAD

**Issue by kilip** [cross-solution/YAWIK#493]
We need to fix travis build for all yawik modules because we now use mongodb extension. Here's what's need to be check/added for each modules:
* add cache for travis build
* add build matrix for each php version (5.6, 7.0, 7.1, 7.2)
* make sure that all modules pass green build on php >=7.0 version

Modules to be check:

- [x] [Orders](https://github.com/yawik/Orders)
- [x] [DemoSkin](https://github.com/yawik/DemoSkin)
- [x] [SimpleImport](https://github.com/yawik/SimpleImport)
- [x] [Solr](https://github.com/yawik/Solr)
- [x] [JobsByMail](https://github.com/yawik/JobsByMail)
- [x] [CompanyRegistration](https://github.com/yawik/CompanyRegistration)
- [x] [StackoverflowApi](https://github.com/yawik/StackoverflowApi)
- [x] [Jobboard](https://github.com/yawik/Jobboard)

@cbleek feel free to assign me for this issue

**Comment by cbleek** [comment]
Hi Toni,

if  I `composer create-project -sdev yawik/standard yawik.org` I get the question `Please select which config file you wish to inject 'Zend\Validator' into`

What should I choose?

```
cbleek@php7-cb:~$ composer create-project -sdev yawik/standard yawik.org
Installing yawik/standard (dev-master e19ef4f6d762d38e0c69832b4355c361c9b85fe9)
  - Installing yawik/standard (dev-master e19ef4f): Cloning e19ef4f6d7 from cache
Created project in yawik.org
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 146 installs, 0 updates, 0 removals
As there is no 'unzip' command installed zip files are being unpacked using the PHP zip extension.
This may cause invalid reports of corrupted archives. Installing 'unzip' may remediate them.
  - Installing composer/installers (v1.6.0): Loading from cache
  - Installing zendframework/zend-component-installer (1.1.1): Loading from cache
  - Installing zendframework/zend-stdlib (3.2.1): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing container-interop/container-interop (1.2.0): Loading from cache
  - Installing zendframework/zend-validator (2.10.2): Loading from cache

  Please select which config file you wish to inject 'Zend\Validator' into:
  [0] Do not inject
  [1] config/modules.config.php
  Make your selection (default is 0):
```

**Comment by kilip** [comment]
Hi @cbleek,

You can choose [0]  Do not inject.

**Comment by kilip** [comment]
I think we can close this issues, all Yawik additional modules have a green build now.
