### ISSUE TITLE
ClearCacheService does not work as expected.

### ISSUE THREAD

**Issue by TiSiE** [cross-solution/YAWIK#505]
I run into several issues with the [ClearCacheService](https://github.com/cross-solution/YAWIK/blob/911e586f7b36bf2fbf6e09a6769279104f4ed19b/module/Core/src/Service/ClearCacheService.php)

* If YAWIK is run within apache, all cached files are owned by the apache user ('www-data' per default)   
  Thus, if the 'clear-cache' command is run from the terminal, an IOException is thrown ('Permission denied') when trying to remove files in a directory owned by the apache user. (The DoctrineMongoODM cache, in particular.  )
This issue does not occur, when running the command as root - but composer does not encourage this.

* The service creates a checksum generated from the timestamp of all files.   
  The Doctrine cache is constantly altered. Each time an Entity is loaded for the first time from the database, a proxy class is generated and stored in the cache dir.   
Meaning: The ClearCacheService will constantly wipe all files, because new proxy classes will be created on nearly every page request.

**Comment by cbleek** [comment]
@TiSiE does it works now as expected?

**Comment by kilip** [comment]
I forget to report back in this issue, ```depth=0``` in line 106 limit finder to find only in the root of cache dir:

https://github.com/cross-solution/YAWIK/blob/a4f149b1d99e574560944a8b6d75f7673b6a0a7b/module/Core/src/Service/ClearCacheService.php#L101-L113

So doctrine cache now is not wiped.

I am also set ```umask(0000)```, which means the file created by php in apache or in console should be writable to everyone.

**Comment by TiSiE** [comment]
Yeah, it works now.
