### ISSUE TITLE
Creating an own organization does not work

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#507]
On a fresh installation via `composer create-project -sdev yawik/standard MyYawik` I cannot "create my organization".

```
Page not found.
The requested controller was unable to dispatch the request.

Controller:
Auth\Controller\Manage
```
![auswahl_521](https://user-images.githubusercontent.com/858642/48217498-cd583400-e387-11e8-94b1-ad3705f187f4.png)

**Comment by kilip** [comment]
This issue relates to wrong loading modules order issue #506, modules should be load in spesific order.

**Comment by cbleek** [comment]
Thank you, works now
