### ISSUE TITLE
Store salary information

### ISSUE THREAD

**Issue by TiSiE** [cross-solution/YAWIK#512]
It is necessary to store salary information in a job entity.

This should be done using a salary entity which will be embedded in a job entity.

The information from this salary entity should then also be used in the jsonLD generated for each job (via the [JsonLD](https://github.com/cross-solution/YAWIK/blob/develop/module/Jobs/src/View/Helper/JsonLd.php) view helper)

Therefor the entity needs all information to fullfill the requirements for the `baseSalary` entry [defined by google](https://developers.google.com/search/docs/data-types/job-posting?hl=en#JobPosting-definition)
(We will ignore ranges as it's very unlikely that a job will be published with a salary range...)

That means, the following properties should be available:
* value (or amount): Integer value
* unit: one of the `unitText` values
* currency: The currency (using a default value according to the locale.)

Additionally - to be able to input values for the salary entity - we need to create a Form and a Fieldset to add the the [Job Form Container](https://github.com/cross-solution/YAWIK/blob/develop/module/Jobs/src/Form/Job.php)

**Comment by sergey-galenko** [comment]
@TiSiE thank you! I'll take this task.
