### ISSUE TITLE
External URL to track applications is not properly sanitized and leads to arbitrary code injection

### ISSUE THREAD

**Issue by mbo-s** [cross-solution/YAWIK#514]
It is possible to inject HTML/Javascript-Code like IFrames into a job offer.

Steps to reproduce:

1. Create a new job https://yawik.org/demo/en/jobs/edit
2. Under "Create job opening" in the menu "Track applications" change Mode to "use external link" and fill in e.g. `javascript:alert('xss');"><script>alert('xss');</script><iframe src="https://www.yawik.org"><rel="`
3. save

You will get to Javascript Messages "XSS" one from the preview and one from the "Track applications"-Menu.  
The Iframe will be injected, too.
![track-applications](https://user-images.githubusercontent.com/9078194/48441165-20b4f280-e78b-11e8-9db9-9c6285ba5923.PNG)

**Comment by cbleek** [comment]
yes, this field should be filtered

let's ask @sergey-galenko , if he can fix this.

**Comment by sergey-galenko** [comment]
I'll take a look on it
