### ISSUE TITLE
ReleaseTools: release command errored.

### ISSUE THREAD

**Issue by TiSiE** [cross-solution/YAWIK#523]
When running the `bin/console release` command, the working directory is not changed correctly.

```
Releasing v0.32.0-RC1 to ~> git@github.com:yawik/pdf.git
Working Directory:  /tmp/yawik/build/pdf
     CMD  git clone git@github.com:yawik/pdf.git .
--> ERR  fatal: destination path '.' already exists and is not an empty directory.__
     CMD  git checkout release-0.32.0
     ERR  Already on 'release-0.32.0'
     OUT  Your branch is up-to-date with 'origin/release-0.32.0'.
     CMD  git tag -s v0.32.0-RC1 -m "Release v0.32.0-RC1 version"
     CMD  git push origin v0.32.0-RC1
     [... ommitting non relevant errors ...]
--> ERR  error: failed to push some refs to 'ssh://git@github.com/cross-solution/YAWIK.git'

```

The first highlighted line already hints that something is going wrong.   
The last line confirms it: Instead of `git@github.com:yawik/pdf.git` it tried to push to `git@github.com/cross-solution/YAWIK.git`, which can only be, if the working directory did not change.

**Comment by kilip** [comment]
@TiSiE I have fix the release command. I have executed this command and you can see the log in [here](https://gist.github.com/kilip/11acade30fe14e39d18c926aaa67eb0c)

**Comment by TiSiE** [comment]
@kilip 
Sorry. It's still not working.
I replaced all commands with a simple `pwd` and that is the output of one `subsplit-tag`:

```
Releasing v0.32.0-RC1 to ~> git@github.com:yawik/applications.git
Working Directory:  /tmp/yawik/build/applications
 CMD  pwd
 OUT  /home/mathias/git/YAWIK-pr-merging
```

**Comment by TiSiE** [comment]
And after a little debugging:

In the Symfonie\Component\Process\Process class line 340-342
```

        if (!is_dir($this->cwd)) {
            @trigger_error('The provided cwd does not exist. Command is currently ran against getcwd(). This behavior is deprecated since Symfony 3.4 and will be removed in 4.0.', E_USER_DEPRECATED);
        }
```

So the directory has to be created to be used as working directory.

**Comment by TiSiE** [comment]
I fixed it temporarely. Will commit it after the RC releasing.
