### ISSUE TITLE
make CoreTestUtils installable with composer

### ISSUE THREAD

**Issue by kilip** [cross-solution/YAWIK#525]
Right now we use ```.gitattributes``` file to ignores test directory:
https://github.com/cross-solution/YAWIK/blob/c74be957b091c431b5a75cec0374c9b03f51d4a7/module/Core/.gitattributes#L1-L3

But since CoreTestUtils needed by other packages like Orders and SimpleImport module we need to make this CoreTestUtils to be installable by composer.

This can be done by subspliting CoreTestUtils directory into yawik/CoreTestUtils, and create composer configuration in ```path/to/yawik/module/Core/test/CoreTestUtils/composer.json```

After completed this CoreTestUtils package needs to be added in this modules:
- [ ] [Orders](https://github.com/yawik/Orders)
- [ ] [SimpleImport](https://github.com/yawik/SimpleImport)
- [ ] [Solr](https://github.com/yawik/Solr)
- [ ] [CompanyRegistration](https://github.com/yawik/CompanyRegistration)

**Comment by TiSiE** [comment]
Yes, absolutely.
But I'd say, we create a dedicated module and add this to the `require-dev` section.

**Comment by TiSiE** [comment]
Test utils now available: https://github.com/cross-solution/phpunit-utils

This will be closed. Each affected module must deal with the integration in its own issues.
