### ISSUE TITLE
zf2htmlpurifier missing in Jobs/composer.json

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#526]
`mikemix/zf2htmlpurifier` is missing as a dependency in module/Jobs/composer.json (I guess)

`
[Thu Nov 29 08:53:38 2018] 127.0.0.1:34308 [500]: /de/jobs/editTemplate/5bff9b008dc1b333168b456e - Class 'zf2htmlpurifier\Filter\HTMLPurifierFilter' not found in /home/cbleek/test/standard/module/Core/src/Filter/XssFilterFactory.php on line 34`

**Comment by kilip** [comment]
Forgive me, I have remove this package because I think it is not used. You can fix this by adding ```mikemix/zf2htmlpurifier|``` in ```path/to/yawik/composer.json``` and ```module/Core/composer.json```

This library is abandoned, we should replace this package in 0.33-dev.

**Comment by cbleek** [comment]
@kilip 

we need to fix this.

Can you take you the time to check, if https://packagist.org/packages/milqmedia/htmlpurifier is an option for a replacement?

**Comment by kilip** [comment]
@cbleek 

Yes, I will check it.

**Comment by kilip** [comment]
@cbleek 

Looks like ```milqmedia/htmlpurifier``` is not maintained too (last update on 2016). But I have found that integrating ezyang/htmlpurifier (used by zf2htmlpurifier) into yawik is not very difficult.

So I just copy and modify a code from zf2htmlpurifier into yawik.

**Comment by kilip** [comment]
@TiSiE I have forget to add ```ezyang/htmlpurifier``` into ```yawik/core``` composer config. The config should be like this:

```json
/path/to/yawik/src/Core/composer.json file:
{
  "require": {
    "ezyang/htmlpurifier": "^4.10",
  }
}
```

**Comment by cbleek** [comment]
@kilip If you can create a release, please add the small change and release it.
