### ISSUE TITLE
InputFilter in AtsMode Form does not seem to work

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#553]
Demo Database contains:

```
        "atsMode" : {
                "mode" : "uri",
                "uri" : "javascript:alert('xss');\"><script>alert('xss');</script><iframe src=\"https://www.yawik.org\"><rel=\"",
                "email" : "test@example.com",
                "oneClickApply" : false,
                "oneClickApplyProfiles" : {

                }
        },
```
URI Mode contains the InputFilter StripTags. It seems, the filter does not work.

https://github.com/cross-solution/YAWIK/blob/master/module/Jobs/src/Form/InputFilter/AtsMode.php#L68

BTW: MODE_EMAIL should use an InputFilter, too.

![Auswahl_237](https://user-images.githubusercontent.com/858642/66297765-96203900-e8f0-11e9-920d-fc0d88bc39f1.png)

**Comment by mbo-s** [comment]
@cbleek This looks like the test data from https://github.com/cross-solution/YAWIK/issues/514

**Comment by cbleek** [comment]
this was fixed
