### ISSUE TITLE
YAWIK ERROR

### ISSUE THREAD

**Issue by Steinbach2019** [cross-solution/YAWIK#557]
https://yawik.org/demo/de/jobs/edit

/var/www/production/releases/13/vendor/zendframework/zend-servicemanager/src/ServiceManager.php:771

`Service with name "Core/MailService" could not be created. Reason: Zend\Mail\Transport\FileOptions::setPath expects a valid path in which to write mail files; received "/build/mails"`

**Comment by cbleek** [comment]
@TiSiE I thougt, that only o config file is missing.

but I think I was wrong. Can you take a look?

**Comment by TiSiE** [comment]
It is just a misconfiguration on "yawik.org/demo" (@cbleek pm me for details)
There is no bug in YAWIK.
