### ISSUE TITLE
Frage Datepicker minDate Option

### ISSUE THREAD

**Issue by StefanieD** [cross-solution/YAWIK#568]
Hallo,

ich habe eine Frage zum Form Element **Core/Datepicker**. Ich möchte, dass nur Tage ab einem bestimmten Datum klickbar sind. Alle Tage in der Vergangenheit sollen deaktiviert sein. Im JQuery Datepicker gibt es dafür die Option **minDate**.
Ich konnte in dem Datepicker Element diese Option nicht finden. Ist das implementiert?

**Comment by TiSiE** [comment]
Zum rendern der Option ins HTML sollte es ausreichen, dem Element ein `data-min-date` Attribut zu geben.

Ich weiß jetzt aber nicht aus dem Kopf, ob beim aktivieren des Formulars per Javascript/JQuery diese Attribute berücksichtigt werden... Ich gehe davon aus - einfach mal ausprobieren.

.. Und das Ergebnis rückmelden :)

**Comment by StefanieD** [comment]
```
$this->add([
            'name'       => 'publishDate',
            'type'       => 'Core/Datepicker',
            'options'    => [
                'label'           => /*@translate*/ 'Earliest starting date',
                'description'     => /*@translate*/ 'Enter the earliest starting date.',
                'disable_capable' => [
                    'description' => /*@translate*/ 'Ask the applicant about the earliest starting date.',
                ],
                'format' => 'd/m/Y',
                'minDate' => 0
            ],
            'attributes' => [
                'data-date-format' => 'dd/m/yyyy',
                'data-language' => 'de',
                'data-min-date' => 0,
                'class' => 'form-control',
                'id' => 'datepicker-publishDate'
            ]
        ]);
```

Ich habe dem Wert data-min-date mal 0, oder '0' oder '2020-06-07' gegeben. Aber im FE sieht es immer noch so aus

![datepicker](https://user-images.githubusercontent.com/1849475/83645912-4f83fb00-a5b3-11ea-8261-1ad4e3e24529.png)

**Comment by TiSiE** [comment]
Wird denn das Attribut in den HTML-Code gerendert?

**Comment by TiSiE** [comment]
Nach https://bootstrap-datepicker.readthedocs.io/en/latest/options.html gibt es keine Option "minDate".

Wohl aber [startDate](https://bootstrap-datepicker.readthedocs.io/en/latest/options.html#startdate), was Deinen Anforderungen entsprechen sollte.

**Comment by StefanieD** [comment]
Das HTML Attribut ist da. 
Aber handelt es sich hier nicht um den JQuery UI Datepicker? So hatte ich das in der yawik core.js gesehen. Dort wird ein Datepicker Object erstellt.
Oder nutzt der Bootstrap Datepicker JQuery UI?
Würde denn das StartDate gehen? Habe mal mit data-start-date probiert, aber keine Änderung.

**Comment by TiSiE** [comment]
Es ist definitiv der Bootstrap Datepicker.

Das Prefix für Datepicker-Attribute ist `data-date`, um das startDate zu setzen, muss man also das Attribute `data-date-start-date` nutzen. Darüber hinaus muss das angegebene Datumsformat  benutzt werden.

Die momentane Implementierung des ViewHelpers lässt es nicht zu, das Datums-Format zu konfigurieren. (Im ViewHelper wird das Element-Attribute überschrieben) (Das ist ein Bug, dazu muss ein Ticket erstellt werden).

Wenn man das alles zusammennimmt, sieht ein funktionierendes Beispiel so aus:
``` php

$this->add([
            'name'       => 'publishDate',
            'type'       => 'Core/Datepicker',
            'options'    => [
                'label'           => /*@translate*/ 'Earliest starting date',
                'description'     => /*@translate*/ 'Enter the earliest starting date.',
                'disable_capable' => [
                    'description' => /*@translate*/ 'Ask the applicant about the earliest starting date.',
                ],
                'format' => 'd/m/Y',
                'minDate' => 0
            ],
            'attributes' => [
                'data-date-format' => 'dd/m/yyyy' // wird leider im ViewHelper zu 'yyyy-mm-dd',
                'data-date-language' => 'de',
                'data-date-start-date' => '2020-06-05', // selbes Datumsformat!
                'class' => 'form-control',
                'id' => 'datepicker-publishDate'
            ]
        ]);
```

**Comment by TiSiE** [comment]
Bitte Bescheid geben, auch wenn es funktioniert.

**Comment by StefanieD** [comment]
Ahh perfekt. Das war es. Mit dem richtigen Prefix funktioniert es. Danke.

Dass das data-date-format überschrieben wird, ist mir auch schon aufgefallen. Ich habe den ViewHelper in meinem Projekt vorerst erweitert. Wollte bei Zeiten dafür einen MR erstellen.
