### ISSUE TITLE
manually add candidates and recruiters

### ISSUE THREAD

**Issue by RagnarDanneskjold** [cross-solution/YAWIK#57]
what is the best way to manually add candidates and recruiters as described here? :
http://yawik.org/2014/03/awesome-fonts/
"An applicant the groups "HR professionals who may see my CV anonymous" could, "complete understanding" or "'m willing to pay for the mediation" Create.
Or a company that specializes in the placement of candidates, groups creates as "candidates for Sales Customer" or "candidate for IT clients".

AND

are there any modules or suggested methods for implementing password auth for recruiters and applicants without social network login?

AND 

what is the suggested process for generating multiple recruiter / admin profiles under one group?

Also

Is there a suggested way to grant limited (varied) access to to the same applicant db (group) for recruiter profiles in one group?

**Comment by cbleek** [comment]
recruiters can now add CVs to a talent pool.
