### ISSUE TITLE
Loader for purge expire jobs should consider "dateModified"

### ISSUE THREAD

**Issue by TiSiE** [cross-solution/YAWIK#579]
Currently, the loader for the purge expire jobs action checks against the "datePublishEnd" or - if not available - "dateCreated".

It certainly makes more sense to check against the "dateModified".

**Comment by cbleek** [comment]
@kilip dateCreated has to be changed to dateModified. Maybe Tests have to be adjusted.

see: 
* [YAWIK : LoadExpiredJobsToPurge.php #34-43](https://github.com/cross-solution/YAWIK/blob/4596f11c5dc065c85d97898309e461639f60dbbb/module/Jobs/src/Listener/LoadExpiredJobsToPurge.php#L34-L43)
* [SimpleImport : JobProcessor.php #188](https://github.com/yawik/SimpleImport/blob/a4eee45c68dfe5cfa2118feba6ca8bcdfb497282/src/CrawlerProcessor/JobProcessor.php#L188)
