### ISSUE TITLE
Tippfehler in Übersetzung (Jobs Modul)

### ISSUE THREAD

**Issue by StefanieD** [cross-solution/YAWIK#584]
Die Message "Publishing successfully finished" wird im Deutschen als "Eingabe erfolgreich angeschlossen" übersetzt. Ich denke hier ist ein Fehler und es sollte "abgeschlossen" heißen ?

In der Datei `Jobs/language/de_DE.po`

**Comment by cbleek** [comment]
Besten Dank für die Info.

Die Übersetzungen werden in https://www.transifex.com/yawik/yawik/dashboard/ gepflegt. Habe es dort korrigiert. Das wird ins nächste Release einfließen

![Auswahl_902](https://user-images.githubusercontent.com/858642/87022896-654e9680-c1d7-11ea-9b7f-3b48e840b1a6.png)

**Comment by StefanieD** [comment]
Perfekt. Dankeschön.
