### ISSUE TITLE
Logout does not work correctly

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#611]
odm-module3 is deployed to https://staging.yawik.org.

You can login with de demo accounts demo/demo, recruiter/recruiter and admin/admin

It's not possible to logout correctly. You'll get an internal Server error. 

You have to remove the remaining cookie before you can open yawik again

![Auswahl_999(788)](https://user-images.githubusercontent.com/858642/102818291-9f040a00-43d1-11eb-913c-a9af9e6f6248.png)

**Comment by TiSiE** [comment]
The database was in use with an YAWIK instance which had the Orders module activated. The orders module uses the settings mechanism to add user settings via the `InvoiceAddressSettings` entity.

This is a known issue in YAWIK and we implemented AttachableEntities to solve this.      
The settings module needs a proper refactoring though.

**Comment by TiSiE** [comment]
Found it. It's an issue in the orders module: https://github.com/yawik/Orders/issues/23

**Comment by cbleek** [comment]
Thank you
