### ISSUE TITLE
Images and Filenames are not displayed

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#612]
# odm module3 Branch

images are missing. https://staging.yawik.org 

![Auswahl_999(792)](https://user-images.githubusercontent.com/858642/102819568-f5724800-43d3-11eb-8da1-2f82142271e4.png)

# master branch

https://yawik.org/demo/

![Auswahl_999(790)](https://user-images.githubusercontent.com/858642/102819535-eab7b300-43d3-11eb-9b31-960db3b5e8aa.png)

**Comment by kilip** [comment]
@cbleek I am start working on this issue.

**Comment by cbleek** [comment]
thank you. Also corrected the file name in the detail view.
