### ISSUE TITLE
double click on save in form container

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#67]
if you double click on the save button in the adress field of an application form, you get this:
![bildschirmfoto 2014-10-21 um 21 56 24](https://cloud.githubusercontent.com/assets/858642/4725847/e0534b8a-595c-11e4-9a7e-d39e9d30b961.png)

Test Form:
http://yawik.org/demo/de/apply/software-developer

**Comment by TiSiE** [comment]
The submit button is now disabled during the ajax request. (and enabled again, when ajax is ready), preventing two (or more) ajax request send almost simultaneously.
