### ISSUE TITLE
[Jobs] HTML Tags in Job title

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#78]
It must not be possible to a HTML Tags into the Jobtitle. If such tags are entered, they should be silently removed before the the value is saved.
 
![auswahl_585](https://cloud.githubusercontent.com/assets/858642/5372433/ee10265e-8048-11e4-9482-e133376f78c7.png)

**Comment by mathias-weitz-cross-solutions** [comment]
Solution is delayed due a common problem by creating forms by constructor and not by service. Services would allow general access to other services.
We are tending to use factories and inject the needed services.
