### ISSUE TITLE
filter JS from job openings

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#82]
currently it's possible to put JS into the tinyMCE inline Editor

http://www.karriere24.com/jobs/de/jobs/view?id=5494bb61d464a3de42dedae8

JS has to be filtered.

**Comment by TiSiE** [comment]
Some notes to clearify the linked diagrams:
These steps has to be done:
* Create a XSS Filter class (implemening \Zend\Filter\FilterInterface)
* Register this filter in the Filter Plugin Manager.   
  This is done by configuring the mapping in the filter plugin manager config, which is found in the main application config under the key "filters" (which is a service manager configuration array)   
e.g. <pre>
     "filters" => array(
          "invokables" => array(
                 "Core/Xss" => "\Core\Filter\XssFilter",
         )
      )</pre>
* Attach this filter to the elements which should be using it.   
  in the case of jobs, the only element currently is "\Core\Form\Element\Editor"
  * Make the element an input provider for \Zend\InputFilter by implementing "\Zend\InputFilter\InputProviderInterface"
  * In the "getInputSpecification()" method, configure the use of the Xss filter
<pre>
    return array(
         ...
        "filters" => array(
               "Core/XssFilter"
        )
</pre>
(Maybe the syntax is slightly different, I'm not sure at the moment.)

**Comment by cbleek** [comment]
https://github.com/cross-solution/YAWIK/commit/4d79d2e5be90096d2d45c13e64f4d880ff11dc4f
