### ISSUE TITLE
editing job-offers: assign organization

### ISSUE THREAD

**Issue by mathias-weitz-cross-solutions** [cross-solution/YAWIK#83]
We have already implemented an organization-entity, that contains various informations about a company.
This entity has to be assigned to a job-offer as a reference. So far you can just enter a name (with no connection to the organization-collection).
Entering the Organization-Name should utilize the lookahead javascript that is also used in the filter for applications.

**Comment by cbleek** [comment]
was done in

https://github.com/cross-solution/YAWIK/commit/73d67668b53106a6cca1ed501a1e8d5ed6eb5877
