### ISSUE TITLE
<basePath>/de/ rewrites to /de

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#85]
http://yawik.org/demo/de/ is redirected to http://yawik.org/de

The rewrite ist propably done because of the default ZF2 .htaccess in the public directory

<pre>
RewriteRule ^(.*)/$ /$1 [R=301,L]
</pre>

The Demo is using the apache directive 

<pre>
Alias /demo /<location-to-YAWIK>/public
</pre>

The rewrite_log starts with
...[rid#7f8cef69b0a0/initial] (3) [perdir <document_root>/] strip per-dir prefix: <document_root>/de -> de
</pre>

So it propably an apache problem.

**Comment by TiSiE** [comment]
Maybe it helps setting the RewriteBase directive?

http://httpd.apache.org/docs/current/mod/mod_rewrite.html#rewritebase

**Comment by mbo-s** [comment]
This is an apache issue: if you use Alias you must set the RewriteBase.
For a safer way this should be handeld by the buildscript.
There are more issues, if yawik does not run in the rootdir: The captcha-image-dir points to /captcha and not to /yawikdir/captcha

**Comment by cbleek** [comment]
so we can close this issue
