### ISSUE TITLE
 An exception was raised while creating "Jobs/RestClient"; no instance returned

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#86]
If you want to approve a new job opening, you get the following error

Ein Fehler ist aufgetreten
An error occurred during execution; please try again later.
Zusätzliche Informationen:
Zend\ServiceManager\Exception\ServiceNotCreatedException

Datei:

    /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php:912

Nachricht:

    An exception was raised while creating "Jobs/RestClient"; no instance returned

Stapelverlauf:

    #0 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(1035): Zend\ServiceManager\ServiceManager->createServiceViaCallback(Array, 'jobsrestclient', 'Jobs/RestClient')
    #1 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(609): Zend\ServiceManager\ServiceManager->createFromFactory('jobsrestclient', 'Jobs/RestClient')
    #2 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(569): Zend\ServiceManager\ServiceManager->doCreate('Jobs/RestClient', 'jobsrestclient')
    #3 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(503): Zend\ServiceManager\ServiceManager->create(Array)
    #4 /var/www/clients/client1/web26/cross-applicant-management/module/Jobs/src/Jobs/Listener/Publisher.php(72): Zend\ServiceManager\ServiceManager->get('Jobs/RestClient')
    #5 [internal function]: Jobs\Listener\Publisher->restPost(Object(Jobs\Listener\Events\JobEvent))
    #6 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Jobs\Listener\Events\JobEvent))
    #7 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('job.accepted', Object(Jobs\Listener\Events\JobEvent), Array)
    #8 /var/www/clients/client1/web26/cross-applicant-management/module/Jobs/src/Jobs/Controller/ManageController.php(352): Zend\EventManager\EventManager->trigger('job.accepted', Object(Jobs\Listener\Events\JobEvent))
    #9 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractActionController.php(83): Jobs\Controller\ManageController->approvalAction()
    #10 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
    #11 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
    #12 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #13 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractController.php(117): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #14 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/Mvc/DispatchListener.php(114): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
    #15 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
    #16 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
    #17 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #18 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(309): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #19 /var/www/clients/client1/web26/cross-applicant-management/public/index.php(32): Zend\Mvc\Application->run()
    #20 {main}

Vorherige Exceptions:

    RuntimeException

    Datei:

        /var/www/clients/client1/web26/cross-applicant-management/module/Jobs/src/Jobs/Services/JobsPublisherFactory.php:43

    Nachricht:

        target for multiposting is missing

    Stapelverlauf:

        #0 /var/www/clients/client1/web26/cross-applicant-management/module/Jobs/src/Jobs/Services/JobsPublisherFactory.php(29): Jobs\Services\JobsPublisherFactory->getConfig()
        #1 /var/www/clients/client1/web26/cross-applicant-management/module/Core/src/Core/Service/RestClientFactory.php(30): Jobs\Services\JobsPublisherFactory->getUri()
        #2 [internal function]: Core\Service\RestClientFactory->createService(Object(Zend\ServiceManager\ServiceManager), 'jobsrestclient', 'Jobs/RestClient')
        #3 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(905): call_user_func(Array, Object(Zend\ServiceManager\ServiceManager), 'jobsrestclient', 'Jobs/RestClient')
        #4 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(1035): Zend\ServiceManager\ServiceManager->createServiceViaCallback(Array, 'jobsrestclient', 'Jobs/RestClient')
        #5 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(609): Zend\ServiceManager\ServiceManager->createFromFactory('jobsrestclient', 'Jobs/RestClient')
        #6 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(569): Zend\ServiceManager\ServiceManager->doCreate('Jobs/RestClient', 'jobsrestclient')
        #7 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(503): Zend\ServiceManager\ServiceManager->create(Array)
        #8 /var/www/clients/client1/web26/cross-applicant-management/module/Jobs/src/Jobs/Listener/Publisher.php(72): Zend\ServiceManager\ServiceManager->get('Jobs/RestClient')
        #9 [internal function]: Jobs\Listener\Publisher->restPost(Object(Jobs\Listener\Events\JobEvent))
        #10 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Jobs\Listener\Events\JobEvent))
        #11 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('job.accepted', Object(Jobs\Listener\Events\JobEvent), Array)
        #12 /var/www/clients/client1/web26/cross-applicant-management/module/Jobs/src/Jobs/Controller/ManageController.php(352): Zend\EventManager\EventManager->trigger('job.accepted', Object(Jobs\Listener\Events\JobEvent))
        #13 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractActionController.php(83): Jobs\Controller\ManageController->approvalAction()
        #14 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
        #15 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
        #16 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
        #17 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractController.php(117): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
        #18 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/Mvc/DispatchListener.php(114): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
        #19 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
        #20 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
        #21 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
        #22 /var/www/clients/client1/web26/cross-applicant-management/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(309): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
        #23 /var/www/clients/client1/web26/cross-applicant-management/public/index.php(32): Zend\Mvc\Application->run()
        #24 {main}

**Comment by mathias-weitz-cross-solutions** [comment]
Configuration for this service (Rest/Client) get tested for availability before calling the service itself.
