### ISSUE TITLE
Mailservice overwrite Recipient fails

### ISSUE THREAD

**Issue by mathias-weitz-cross-solutions** [cross-solution/YAWIK#88]
In the mailservice, method "send", there is a query "null !== $this->overrideRecipient".
overrideRecipient is false, if there is no override, so there still will be a mail sended to false.

**Comment by TiSiE** [comment]
Not just one additional mail but ALL mails will be send to "false" EXCLUSIVELY. This is the CRITICAL buggy behaviour we have to address.
