### ISSUE TITLE
Unused Code

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#89]
see https://scrutinizer-ci.com/g/cross-solution/YAWIK/inspections/6f13da4f-1e7e-4e0f-98ce-8f3ca6a644ff/code-structure/operation/Organizations%5CController%5CIndexController%3A%3AeditAction#inspectioncomment-596753448

**Comment by TiSiE** [comment]
Unnecessary. Used for debugging.

**Comment by cbleek** [comment]
was closed in 068213eb6a19f158ac084ce6d72e7a1d157b71d4
