### ISSUE TITLE
Register twice display the form again with no message

### ISSUE THREAD

**Issue by mbo-s** [cross-solution/YAWIK#93]
If you register the first time you get an email to confirm your account.
If you do not confirm the account, but register again with the same email the form will display again with no error message.
Better would be a message:
The Email is already registered, Lost your password, resend confirmation mail (if the account is not confirmed)

**Comment by mbo-s** [comment]
That is no an issue regarding yawik. I used an modified layout.
The Javascript for the notify should be loaded after the core.ini.js Javascript
Something that should be mentioned in http://yawik.readthedocs.org/en/latest/modules/core/notifications.html

Right order to display the notifications
$this->configheadScript()
        ->prependFile($this->basepath('Core/js/core.init.js'))
        ->prependFile($this->basePath('/Core/js/pnotify.custom.min.js'));

**Comment by TiSiE** [comment]
> $this->configheadScript()
> ->prependFile($this->basepath('Core/js/core.init.js'))
> ->prependFile($this->basePath('/Core/js/pnotify.custom.min.js'));

This will load the notify script BEFORE the core script.

This is right:

    $this->configheadScript()
    ->prependFile($this->basepath('Core/js/core.init.js'))
    ->appendFile($this->basePath('/Core/js/pnotify.custom.min.js'));

or 

    $this->configheadScript()
    ->prependFile($this->basepath('Core/js/core.init.js'))
