### ISSUE TITLE
Backlink to job broken/missing

### ISSUE THREAD

**Issue by mbo-s** [cross-solution/YAWIK#95]
The Backlink to the joboffer is broken:
http://yawik.org/demo/de/apply/Projektmanager-produktentwicklung

Sie bewerben sich auf die Stelle "&lt;a href="" title="Klicken, um die Stellenanzeige zu öffnen"&gt;Projektmanager (m/w) Produktentwicklung 2&lt;/a&gt;" der Firma "CROSS Solution"

in the applications details
/de/applications/JOBID
Bewerbung auf: &lt;a href=""&gt;Projektmanager (m/w) Produktentwicklung 2&lt;/a&gt;

In the applications overview the links in the column joboffer points to the applicationdetailsview and not to the job

**Comment by cbleek** [comment]
Hi mbo-s

You're right. Thanks for reporting!

Regards,

Carsten

-- 
Cross Solution           | Carsten Bleek
Diemelstraße 2-4         | Tel: 069-71910361
60486 Frankfurt am Main  | Fax: 069-71910369
http://cross-solution.de | bleek@cross-solution.de
