### ISSUE TITLE
Wrong Joblink

### ISSUE THREAD

**Issue by mbo-s** [cross-solution/YAWIK#96]
After login in the overview of the applicants
http://yawik.org/demo/de/applications?clear=1
The link does not lead to the job, but the column indicates this
![yawik-missingjoblink](https://cloud.githubusercontent.com/assets/9078194/6585525/b2c6ed8c-c772-11e4-88bb-c8d0888e560b.jpg)

Linktarget: http://yawik.org/demo/de/applications/54f9a175ae02599a6b24cc46

**Comment by TiSiE** [comment]
This is indeed irritating. 

As we have the pencil-Button at the end of the column, we should consider to point the link to the job.
