### ISSUE TITLE
Register as an logged in user

### ISSUE THREAD

**Issue by mbo-s** [cross-solution/YAWIK#99]
You can regsiter a new account if you are logged in

go to 
http://yawik.org/demo/en
log in with demo/demo
open http://yawik.org/demo/en/auth/register and create a new account
![yawik-register-logged-in](https://cloud.githubusercontent.com/assets/9078194/6586435/ad98ed7c-c779-11e4-87b0-fe4279e57249.jpg)

**Comment by mbo-s** [comment]
Resetting your password is possible too
http://yawik.org/demo/en/auth/forgot-password

**Comment by TiSiE** [comment]
Seems to be missing ACL rules.

**Comment by cbleek** [comment]
If it's that simple, we should fix it in 0.19
